### ISSUE TITLE
The API key appears to have insufficient quota

### ISSUE THREAD

**Issue by DeepCoreB4** [enricoros/big-agi#104]
Hi..[enricoros](https://github.com/enricoros)
The structure of the UI, nice work!! I Like the possibility to switch the dark/white Mode!!

But something not working! Im using the free ChatGPT API but doesn't working, i got this error in the Local Server :

Error in WebUi LocalHost;

`The API key appears to have insufficient quota. Please check [your usage](https://platform.openai.com/account/usage) and make sure the usage is under [the limits](https://platform.openai.com/account/billing/limits).`

and from the console in VsCode:

`_Fetch request failed: [Error: 429 · Too Many Requests · {"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}]_`

But if i using the Original ChatGpt  on the Web everything works fine!

Is there a fix?

Thanks for your work 👍🏾 
will give 5 Stars if i got this to work

**Comment by enricoros** [comment]
Hi and thanks for the question. The API key for OpenAI GPT3.5/4 is a separate product than ChatGPT.
The key is "pay as you go" to perform many API queries, while the ChatGPT product is a monthly subscription to the chat only.
In your case it seems like there are issues with the key having run out of credits, and would need more credits to use the API.
Hope this clarifies.

**Comment by enricoros** [comment]
The error is not coming from big-AGI, but from OpenAI itself. So there's nothing we can do to solve their error :)

**Comment by p6297** [comment]
You have to add your credit card details to use the api.
