### ISSUE TITLE
Issue - Unhandled Runtime Error

### ISSUE THREAD

**Issue by KazeroG** [enricoros/big-agi#105]
Console Log : `Fetch request failed: [Error: Missing required parameters: api, model, messages]`

The first test message works, but not the Chat : 
![image](https://user-images.githubusercontent.com/17680194/235864782-ee2c809c-1519-4520-9272-f07cdcf4956e.png)

Error screenshot :
![image](https://user-images.githubusercontent.com/17680194/235864219-8a37373f-d899-4ba8-88f7-813958615585.png)

**Comment by enricoros** [comment]
Looked into this, but can't find the cause. This is for local development, correct? Localhost:3000? Has this presented itself again?

You should take a look at `pages/api/openai/chat` and print (console.log) the `requestBodyJson` variable.
Seems like the POST request to the API handler did not have the correct Body.

**Comment by enricoros** [comment]
The code has been overhauled - I believe this is not an issue anymore.
