### ISSUE TITLE
[Feature Request] Support Azure OpenAI 

### ISSUE THREAD

**Issue by PeterDaveHello** [enricoros/big-agi#107]
OpenAI currently doesn't seem to have SLA but Azure OpenAI has 99.9% SLA, also Azure OpenAI has more region, with higher reliability, will be great if we could switch to use Azure OpenAI easily. Thanks!

Reference:

- [azure.microsoft.com/en-us/products/cognitive-services/openai-service](https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/)
- [azure.microsoft.com/en-us/blog/chatgpt-is-now-available-in-azure-openai-service](https://azure.microsoft.com/en-us/blog/chatgpt-is-now-available-in-azure-openai-service/)

**Comment by enricoros** [comment]
I can't get access. One must be registered with a company email just to get access to the OpenAI Azure portal.

**Comment by PeterDaveHello** [comment]
> I can't get access. One must be registered with a company email just to get access to the OpenAI Azure portal.

Maybe I can help with that 😄

**Comment by enricoros** [comment]
I've requested access. I'll need the approval, and then I will need the gpt4 approval.

**Comment by PeterDaveHello** [comment]
> I've requested access. I'll need the approval, and then I will need the gpt4 approval.

Let me know if you'd like a temporarily available access that I can support ;)

**Comment by enricoros** [comment]
@PeterDaveHello sure I'll let you know - I'm forcing myself thought the process so I can then document what people should do to get access. Do you know how the API is called? Is it with an apikey like OpenAI, or is it different?

**Comment by PeterDaveHello** [comment]
@enricoros it's similar but different.

The API endpoint URL will look like this:

`https://RESOURCE_NAME.openai.azure.com/openai/deployments/DEPLOYMENT_NAME/completions`

`RESOURCE_NAME` is the name of instance/resource created on Azure OpenAI, `DEPLOYMENT_NAME` is the model deployment name, and the use will need to provide the API endpoint, deployment name, and the API key to access it.

Maybe this will help:

- https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-03-15-preview/inference.json
- https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2023-05-15/inference.json

**Comment by ovived** [comment]
I have Azure32k access would love to use it on this Big AGI platform. any chances someone does a pull for adding support?

**Comment by enricoros** [comment]
@ovived @PeterDaveHello - I have Azure support in a branch, however, it requires me to add those services in the console. I thought was more similar to OpenAI, where you just need the API key, but in this case we need to deploy networks, and I don't have access to deploy GPT4.

If you DM me on Discord, maybe you can point me to a deployment and give me a temporary key, so I can validate and enable the support on main.

**Comment by treyreynolds** [comment]
Hey @enricoros I am interested in your work toward Azure OpenAI support as I have a use case that requires more TPM than I can currently get from GPT-4. I have a key and deployment of GPT-3.5-Turbo-16k but don't have access to GPT-4 in my Azure account yet.

**Comment by PeterDaveHello** [comment]
@enricoros I have problem using Discord and can't DM you on X(Twitter) without a subscription 😓

**Comment by Qualizorg** [comment]
Hello, any progress regarding this feature?

**Comment by enricoros** [comment]
@Qualizorg - Yes! This is done :) Azure OpenAI, including GPT-4-32k is working great, and natively.
Enjoy! @PeterDaveHello , @treyreynolds @ovived
