### ISSUE TITLE
No openai?

### ISSUE THREAD

**Issue by orophix** [enricoros/big-agi#111]
Can this be run without openai by using localai?

**Comment by enricoros** [comment]
Yes. We have basic support, but needs a few local lines of code changed (Model IDs).
There's a PR coming up now for more.

**Comment by enricoros** [comment]
See https://github.com/enricoros/big-agi/pull/112 .

**Comment by orophix** [comment]
So I built and tested it but it still wants the openai api key. Also the local model doesn't appear in the drop down.

**Comment by enricoros** [comment]
Watch this branch: https://github.com/enricoros/big-agi/compare/main...feaure-model-sources 
there are huge changes coming, with regard to supporting multiple models. It's a big overhaul.
