### ISSUE TITLE
[bug] stop button doesn't work

### ISSUE THREAD

**Issue by Geczy** [enricoros/big-agi#114]
press stop while it's generating, and it will keep generating

**Comment by enricoros** [comment]
Thanks for the report. Will look into it.

**Comment by enricoros** [comment]
@Geczy I can't tell. Is it the button that is grayed out, or do you click and nothing happens?
Any message on the console (F12, Esc on Chrome)? What device/Browser are you on?

**Comment by Geczy** [comment]
i click and the chat continues writing

you cant tell? did you try it yourself?

**Comment by enricoros** [comment]
Works for me, that's why I'm asking details.

**Comment by enricoros** [comment]
Thanks for sharing this, I was wondering how to reproduce. I see something strange going on with the network requests. I'll try to investigate despite not being on Mac.

**Comment by Geczy** [comment]
@enricoros any ideas about that yet? is there anything else i can try? different browser maybe?

**Comment by Geczy** [comment]
i tested it in firefox and it does work there to stop ! so it looks like a chrome issue?

**Comment by enricoros** [comment]
I know that chrome works on windows. Hmmm. On the other hand chrome on macOS also does a poor job of speech recognition, to the point i disabled the whole feature. Very weird.
Thanks for saying it works on Firefox!

**Comment by githubmilind** [comment]
I can see it is working on Windows Chrome. Is it fixed?

**Comment by enricoros** [comment]
Correct, fixed long ago.
