### ISSUE TITLE
Input: 42,020 tokens · Limit: 254 tokens compression needed ≥ 16543 %

### ISSUE THREAD

**Issue by ivan-vilches** [enricoros/big-agi#123]
i did this:
git clone https://github.com/enricoros/big-agi.git
cd big-agi
npm install
npm run dev

i use mac m1 , mac os ventura 13.4 (22F66)
and chrome 114.0.5735.90

when i upload a light pdf i got this on the screenshot

<img width="466" alt="Captura de pantalla 2023-06-05 a la(s) 16 10 35" src="https://github.com/enricoros/big-agi/assets/982720/488c6214-226d-4278-8898-ba7a0de2c5e6">

**Comment by psociety** [comment]
That's because this project doesn't use vectors/embeddings, so you can't use big files.
Related issue: https://github.com/enricoros/big-agi/issues/101

**Comment by enricoros** [comment]
Closed, invalid - does not mention a bug or request, only shows one of the features.
