### ISSUE TITLE
[bug] Paste Code button does not work on Firefox

### ISSUE THREAD

**Issue by kalinon** [enricoros/big-agi#124]
Clicking the button throws the following console error:

```
Uncaught (in promise) TypeError: navigator.clipboard.read is not a function
```

Browser: Firefox 113.0.2 

This works in chrome

**Comment by kalinon** [comment]
This seems relevant: https://stackoverflow.com/questions/67440036/navigator-clipboard-readtext-is-not-working-in-firefox

**Comment by enricoros** [comment]
Thanks for pointing out the thread as well.
What can we do about Firefox? Remove the "Paste" button on Firefox, so people would use CTRL+V (or drag a text/file) instead?

**Comment by kalinon** [comment]
@enricoros i would grey it out if that feature is not enabled? im not a JS expert on how to check if it is. I was able to enable the permission in my browser and it works now.

Or we can just add documentation on how to enable it for firefox:

1.  navigate to `about:config`
2. set `dom.events.asyncClipboard.read` to `true`

**Comment by enricoros** [comment]
Firefox still doesn't allow the clipboard access, despite many requesting it.
Tracking:  https://bugzilla.mozilla.org/show_bug.cgi?id=1809106

**Comment by enricoros** [comment]
Completed by downgrading to no clipboard read on systems that don't support it. Users won't miss this specific feature (they can attach or CTRL+V regularly). 

If the upstream Firefox issue gets resolved (high demand!) then this can be reverted - was hoping it would be resolved by Firefox by now: https://bugzilla.mozilla.org/show_bug.cgi?id=1809106
