### ISSUE TITLE
Important Feature Request(s) 

### ISSUE THREAD

**Issue by vaibhavard** [enricoros/big-agi#131]
1.**One click Conversation Clear** (Since the history - conversation - clear button does not work for me
![image](https://github.com/enricoros/big-agi/assets/57561743/3644fc98-70c3-431c-86f5-07b69c78e69a) ) 

2.**Bing AI (Can replace and enhance "/react" , Bard Integration** 
3.Increased ASR Listening Duration (So you dont have to click **microphone button** again and again)
4.**OpenAI Embedding Based PDF Q&A**

These are from the bugs  i encountered when i was using the app...

**Comment by enricoros** [comment]
> One click Conversation Clear

Updated the History menu to be more clear - it's the Sent Messages history. To clear the chat, click on the "Reset" button in the menu:
![image](https://github.com/enricoros/big-agi/assets/32999/4ddd21f3-8fb0-41ad-a691-c31035bac87a)

**Comment by enricoros** [comment]
> OpenAI Embedding Based PDF Q&A

There are 2PRs for this, see video of #117, and #122. Give it a look. It's hard to productize without impacting existing users.

**Comment by vaibhavard** [comment]
### Thanks for the quick response 😀. This project is really very helpful!

>  I don't know if Bing AI has an API. 

You can use this : https://github.com/waylaidwanderer/node-chatgpt-api ,https://github.com/tuhinpal/bingchat-api 

>Unfortunately the Chrome API closes the connection so quickly as soon as silence is detected. Hint, use CTRL+M to avoid clicking again. Otherwise we'll need to re-arm the Mic using our own timers. Not easy to get it right.

Cant you restart it on our own backend?..Maybe, you can experiment with big-agi\src\common\components\useSpeechRecognition.ts. I tried the togglerecording but it does not work. (PS:I am very new to TYPESCRIPT)
```
        instance.onresult = (event) => {
          if (!event?.results?.length) return;
          let transcript = event.results[event.results.length - 1][0].transcript;
          // shall we have these smarts?
          transcript = (transcript || '')
            .replaceAll(' comma', ',')
            .replaceAll(' exclamation mark', '!')
            .replaceAll(' period', '.')
            .replaceAll(' question mark', '?');
          if (transcript)
            onResultCallback(transcript);
          toggleRecording(); // restarts recording (Currently does not work)

        };
```

**Comment by enricoros** [comment]
I'm also a big user of the Mic, have a couple of ideas in mind,

**Comment by enricoros** [comment]
> 3.Increased ASR Listening Duration (So you dont have to click **microphone button** again and again)

@vaibhavard Mic support has been overhauled. Works best on Chrome/Windows. LMK if it works for you.

**Comment by vaibhavard** [comment]
Thanks A lot for this feature ..Sorry for the delay in reply...The feature works as intended😀😀
