### ISSUE TITLE
PS C:\Users\Dell User\big-agi> npm install npm ERR! code EJSONPARSE

### ISSUE THREAD

**Issue by DMTarmey** [enricoros/big-agi#132]
PS C:\Users\Dell User\big-agi> npm install
npm ERR! code EJSONPARSE
npm ERR! path C:\Users\Dell User\big-agi/package.json
npm ERR! JSON.parse Unexpected token "<" (0x3C) in JSON at position 1331 while parsing near "...s/uuid\": \"^9.0.2\",\r\n<<<<<<< Updated upst..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell User\AppData\Local\npm-cache\_logs\2023-06-28T10_25_11_854Z-debug-0.log
PS C:\Users\Dell User\big-agi> npm audit fix --legacy-peer-deps
npm ERR! code EJSONPARSE
npm ERR! path C:\Users\Dell User\big-agi/package.json
npm ERR! JSON.parse Unexpected token "<" (0x3C) in JSON at position 1331 while parsing near "...s/uuid\": \"^9.0.2\",\r\n<<<<<<< Updated upst..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell User\AppData\Local\npm-cache\_logs\2023-06-28T10_25_54_214Z-debug-0.log
PS C:\Users\Dell User\big-agi>

**Comment by enricoros** [comment]
Mr, you don't really know what you are doing here.
