### ISSUE TITLE
Port connection error 

### ISSUE THREAD

**Issue by DMTarmey** [enricoros/big-agi#134]
✔ Network big-agi_default      Created                                                 1.6s
 ✔ Container big-agi-big-agi-1  Created                                                12.9s
Attaching to big-agi-big-agi-1
big-agi-big-agi-1  | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
big-agi-big-agi-1  |  [TypeError: fetch failed] {
big-agi-big-agi-1  |   cause:  [Error: connect ECONNREFUSED 172.18.0.2:443] {
big-agi-big-agi-1  |   errno: -111,
big-agi-big-agi-1  |   code: 'ECONNREFUSED',
big-agi-big-agi-1  |   syscall: 'connect',
big-agi-big-agi-1  |   address: '172.18.0.2',
big-agi-big-agi-1  |   port: 443
big-agi-big-agi-1  | }
big-agi-big-agi-1  | }
big-agi-big-agi-1  | api/openai/stream-chat error: [Error: [OpenAI Issue] TypeError: fetch failed · Error: connect ECONNREFUSED 172.18.0.2:443]                                                                               ect ECONNREFUSED 172.18.0.2:443]
big-agi-big-agi-1  |  [TypeError: fetch failed] {
big-agi-big-agi-1  |   cause:  [Error: connect ECONNREFUSED 172.18.0.2:443] {
big-agi-big-agi-1  |   errno: -111,
big-agi-big-agi-1  |   code: 'ECONNREFUSED',
big-agi-big-agi-1  |   syscall: 'connect',
big-agi-big-agi-1  |   address: '172.18.0.2',
big-agi-big-agi-1  |   port: 443
big-agi-big-agi-1  | }
big-agi-big-agi-1  | }
big-agi-big-agi-1  | api/openai/stream-chat error: [Error: [OpenAI Issue] TypeError: fetch failed · Error: connect ECONNREFUSED 172.18.0.2:443]ect ECONNREFUSED 172.18.0.2:443]
unexpected EOF
PS C:\Users\Dell User\big-agi>

**Comment by enricoros** [comment]
This place is not "> /dev/null".
