### ISSUE TITLE
Typing D when renaming chat selects delete all button instead.

### ISSUE THREAD

**Issue by tmikaeld** [enricoros/big-agi#136]
When typing a name for a chat, typing d character will select the "delete all" button and hitting enter.. well, let's say I learned this the hard way..

**Comment by enricoros** [comment]
I'm really sorry to hear; will try this out, and will be hard to track (depends on the underlying UX framework).
To hint: Browser and OS?

**Comment by tmikaeld** [comment]
It's absolutely fine 👍 

Thanks for looking into it, MacOS Ventura 3.4 with Chrome (latest)

**Comment by enricoros** [comment]
Debugged the tab order, should be fine now. The 'cancel' button takes precedence.
