### ISSUE TITLE
Add syncing with google drive or simmilar

### ISSUE THREAD

**Issue by VaheDanielyan** [enricoros/big-agi#149]
I love this app, but the feature is missing to make my experience complete.

**Comment by enricoros** [comment]
Thanks, will look into it, I agree.

**Comment by VaheDanielyan** [comment]
I am a c++ developer, but still if I can help please tell me

**Comment by enricoros** [comment]
I saw one app doing Google drive sync, but it said that every hour the user needs to re-login, and to use it from only one device at a time otherwise chats will be overwritten.

What's the ideal flow for this feature, and what's the minimum viable product for this?

**Comment by VaheDanielyan** [comment]
Well lets forgot the google drive part. What's really needed is a way to sync chats across devices. 
Doesn't have to be google drive.

**Comment by enricoros** [comment]
Yep. Looking for the easiest alternative that still leaves the data with the user (so you don't need to trust the deployment admin to not look into your data).

Would you Export/Import select chats, or all of the chats at once?
Would you need merging? (I don't think I can implement this at this point, it's a hard problem in computer science, especially without a central server)

**Comment by enricoros** [comment]
For now the "Backup All" option has been added. (Right Menu > Export > Backup All).

**Comment by enricoros** [comment]
Closing for inactivtiy. Recently a new Sharing mechanism has been added. Moreover the Import/Export options are really broad, and one can save the export on Google Drive.

**Comment by enricoros** [comment]
Thanks for the input @Svk1190 , great find.
