### ISSUE TITLE
Feature: Import conversation from ChatGPT to Big AGI.

### ISSUE THREAD

**Issue by Honkychunkymonkey** [enricoros/big-agi#150]
Sometimes, while I'm using GPT-4 on the ChatGPT frontend, I forget how much I'm using it and run out of messages. I'd like a feature where you could Import a chat from the ChatGPT frontend to BigAGI and continue the conversation there.

**Comment by enricoros** [comment]
I like the idea, what is the best way to export a conversation from ChatGPT? If we have the export we can likely load it.

**Comment by Honkychunkymonkey** [comment]
You can share a link to a conversation, you could probably load it from there. [Here's](https://chat.openai.com/share/76d74731-02f7-413c-b93e-60520cde4658) an example of the shared link.

**Comment by enricoros** [comment]
@Honkychunkymonkey, this has been implemented. Is it working for you? deploying on big-agi.com.

**Comment by Honkychunkymonkey** [comment]
> @Honkychunkymonkey, this has been implemented. Is it working for you? deploying on big-agi.com.

Yes! It does work, but there is one slight issue if the previous conversation used any plugin, it messes with the JSON and gives an error: [as shown in this pastebin](https://pastebin.com/sSci1SNJ)
