### ISSUE TITLE
[I18N] Spanish and Italian translation

### ISSUE THREAD

**Issue by johnfelipe** [enricoros/big-agi#151]

**Comment by enricoros** [comment]
Hi @johnfelipe - we don't have an i18n framework yet; we should. Would take some time to do the full porting, and it's not a priority yet. However, if you want to work on it we can figure something out.

One option for you would be to translate all the strings that are visible directly on the source code, and submit a pull request for that. This way I can prioritize the strings to translate and extract those with a i18n framework.

**Comment by enricoros** [comment]
Added original issue to the roadmap, closing this as dubplicate.
