### ISSUE TITLE
OpenRouter - Http Header not provided

### ISSUE THREAD

**Issue by max00346** [enricoros/big-agi#156]
I just tryed to use the new implemented support for openrouter.ai, but I get an error message about the http header not provided.

Error message:
[OpenAI Issue] Error: 400 · Bad Request · {"error":{"message":"Please set an \"HTTP-Referer\" header with the URL of your app","code":400}}

**Comment by amazingjoe** [comment]
Check out this Javascript snippit found in OpenRouters docs

const chat = new ChatOpenAI(
  {
    modelName: "anthropic/claude-instant-v1",
    temperature: 0.8,
    streaming: true,
    openAIApiKey: $OPENROUTER_API_KEY,
  },
  {
    basePath: $OPENROUTER_BASE_URL + "/api/v1",
    baseOptions: {
      headers: {
        "HTTP-Referer": "https://localhost:3000/",
        "X-Title": "Langchain.js Testing",
      },
    },
  }
);

**Comment by enricoros** [comment]
@max00346 @amazingjoe - fixed, OpenRouter support has officially landed.
