### ISSUE TITLE
Feature request: Chat categories/folders

### ISSUE THREAD

**Issue by tmikaeld** [enricoros/big-AGI#162]
As discussed [here](https://github.com/enricoros/big-agi/pull/158#issuecomment-1727063027) and [here](https://github.com/enricoros/big-agi/issues/137#issuecomment-1676479126).

Something like this:

![image](https://github.com/enricoros/big-agi/assets/907195/ff85751e-0e9b-48d5-a47e-b73dbc692430)

Or even better, a full [chat navigator/filter dialog](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/). 
This would avoid lagging browser due to DOM size and would also work on mobile.

Something like a [drill-down](https://jcoreio.github.io/react-router-drilldown) would also work.

**Comment by enricoros** [comment]
@tmikaeld: @joriskalz has completed this feature, and we are releasing it today. Can you give us feedback regarding that feature (try drag/drop also!) and this ticket?

**Comment by enricoros** [comment]
@Ashesh3 @tmikaeld - shipping the Folders support (with drag/drop) in 1 hour. Can you try it out and let us know your feedback?

**Comment by enricoros** [comment]
@Ashesh3 @tmikaeld - shipping the Folders support (with drag/drop) in 1 hour. Can you try it out and let us know your feedback?
