### ISSUE TITLE
Support for Cloudflare AI Gateway?

### ISSUE THREAD

**Issue by centminmod** [enricoros/big-agi#164]
Maybe possible to add support for Cloudflare AI Gateway https://developers.cloudflare.com/ai-gateway/get-started/connecting-applications/ ? and https://developers.cloudflare.com/ai-gateway/tutorials/deploy-aig-worker/

> endpoint: the pathname of the provider API you’re trying to reach. For example, on OpenAI it can be chat/completions, and for HuggingFace this might be bigstar/code. See more in the sections that are specific to each provider.

**Comment by jontybrook** [comment]
I've just made a PR to add support for OpenAI Cloudflare AI Gateway endpoints. See here: https://github.com/enricoros/big-agi/pull/168

**Comment by enricoros** [comment]
@jontybrook @centminmod - PR merged! Thanks for the contribution. Closed in https://github.com/enricoros/big-agi/commit/05097af27b6b1cc8a30bb2f5bcae15f576a2ea6d

Can you test it and let me know?

You can your CloudFlare OpenAI base URL ("https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai") in the "API Host" field in the UI (Models > OpenAI > Advanced).

**Comment by centminmod** [comment]
@enricoros tried to build but ran into an issue https://github.com/enricoros/big-agi/issues/174 :)

**Comment by centminmod** [comment]
@enricoros thanks for the workaround in #174 - managed to build it and test your Cloudflare AI Gateway implementation and so far works. Just one thing the URL isn't `https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai` but `https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/YOUR_GATEWAY_NAME/openai` where `YOUR_GATEWAY_NAME` is the name you used to create the AI Gateway

![image](https://github.com/enricoros/big-agi/assets/5899584/39a7cb27-6133-485e-8d9b-a5e34951c30b)
