### ISSUE TITLE
Wrong API endpoint for GPT3.5-turbo-instruct

### ISSUE THREAD

**Issue by namnx228** [enricoros/big-agi#169]
When switching to GPt3.5-turbo-instruct, got this issue:
[OpenAI Issue] Error: 404 · Not Found · {"error":{"message":"This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?","type":"invalid_request_error","param":"model","code":null}}

**Comment by enricoros** [comment]
Fixed. Making them available in the Chat UI was misleading. They can be used behind the scenes (e.g. for titling/summarizing) but not for Chat. Thanks for reporting.
