### ISSUE TITLE
Helicone for Claude

### ISSUE THREAD

**Issue by renatoch** [enricoros/big-agi#173]
Just to know: Is it in the roadmap to add support for Helicone using Claude? Anything in progress on this subject?
Any suggestions on temporary alternatives, even if worse? :)
Thanks

**Comment by enricoros** [comment]
Done and works great. Simply set the Helicone key to the Anthropic vendor setup, and calls will be routed through the dashboard.
![image](https://github.com/enricoros/big-agi/assets/32999/8711db92-d76a-4f51-b5aa-91c005e8658f)

Verified on chat ('chat' streaming model) and generation (e.g. chat auto-title).
![image](https://github.com/enricoros/big-agi/assets/32999/231c2a13-94e3-496c-9c93-0268ebdcd58a)
