### ISSUE TITLE
Anthropic Not Working

### ISSUE THREAD

**Issue by saliksik** [enricoros/big-agi#176]
Hello,

Thank you for the awesome web app. I am writing to inform you that Anthropic integration is not working. I am always getting the following error:

[Issue] Anthropic - Forbidden (403) · {"error":{"type":"forbidden","message":"Request not allowed"}}

I have a valid Anthropic API key and direct access.

**Comment by saliksik** [comment]
Update: It's working now, maybe Anthropic API is down when I tested it.

**Comment by enricoros** [comment]
Correct it must have been an issue with the Anthropic servers.

The error is a response returned straight from the Anthropic servers, and we can assume that the key is valid.

Just for reference, an invalid key would return:
```
[OpenAI Issue] Error: 401 · Unauthorized · {"error":{"type":"authentication_error","message":"Invalid API Key"}}
```

Great that's working now. Sometimes even the OpenAI API is down and returns error codes.
