### ISSUE TITLE
Ollama Support

### ISSUE THREAD

**Issue by peperunas** [enricoros/big-agi#179]
Hello everyone,

First of all, great work. The project grew very fast and it's a must-have in my tools!

Any plans to integrate with Ollama (that offers an API endpoint already)?

Ollama: https://ollama.ai/
Ollama API: https://github.com/jmorganca/ollama/blob/main/docs/api.md

**Comment by enricoros** [comment]
@peperunas thanks, would be happy to do it. I don't own a Mac at the moment, and my Linux machine needs some reimagining.

Any way I can get access to a remote ollama instance for development?

Which functionality is needed? (As I can't see how it works). Usually every model provider has: 1. List models, 2. Chat generate (non streaming), 3. Chat generate (streaming)

 - is streaming supported?
 - do we need to support the other APIs (pull, push, create, show, etc..)

**Comment by peperunas** [comment]
Hello @enricoros, this project [1] implements a rudimentary WebUI for Ollama, maybe it can be helpful?

I can say that, after trying that project that:
- Listing models is supported
- Streaming is supported
- I don't know if chat generate (non streaming) is supported

[1]: https://github.com/ollama-webui/ollama-webui

**Comment by peperunas** [comment]
Also, small addendum, I'd more than happy to financially sponsor for the implementation of the feature!

**Comment by enricoros** [comment]
Update on this - there has been progress, but the ollama API is less than ideal to work with. At the moment we can pull new models, list models, but not create streaming completions yet. This is because ollama has a different streaming convention than the usual SSE that everyone else is doing, and as such will require a rewrite of the streaming pipeline :(

**Comment by enricoros** [comment]
Ollama is fully supported.

### List Models
![image](https://github.com/enricoros/big-agi/assets/32999/7a2198a5-d4e7-4175-bc89-7989efc30ad7)

### Admin (Pull) Models
![image](https://github.com/enricoros/big-agi/assets/32999/e95a769a-61bc-4348-a48d-d22279a4735d)

### Streaming text generation
![image](https://github.com/enricoros/big-agi/assets/32999/b450e002-eb50-46ff-ad5b-bcc138ab6a41)

This was PAINFUL - the Ollama project deviates in Stream encoding, Event encoding, URLs, Headers, POST Body's from OpenAI and likes.

**Comment by peperunas** [comment]
Hello @enricoros, this in fantastic. I tested it and it works well!

Thank you very much, outstanding work! Is there a way I can donate to the project? Maybe apply for the Github sponsorship program?

**Comment by enricoros** [comment]
Thanks for testing and using it. I love how fast it works. The "pull" function is a bit slow to me, but administration is probably better done on cmdline for ollama.

No need for donations, but tell all your friends and colleagues to use it :) spread the word.

**Comment by peperunas** [comment]
Oh well, I have already been a PR for quite a while!
