### ISSUE TITLE
gpt-4 Turbo 1106: constrain max output to 4096

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-agi#181]
Right now we do 1/4th of the window size - but 1106 has max of 4096, so it should be set to that.

**Comment by centminmod** [comment]
Yeah set at 2048 got error, 4096 okay

![image](https://github.com/enricoros/big-agi/assets/5899584/1d675331-d0da-4919-ad17-7ea15e27d31a)

**Comment by centminmod** [comment]
small world - CF MVP username?

**Comment by tmikaeld** [comment]
@centminmod **Thomas4** but i fell off after switching to Deno instead. The community was very nice though <3
