### ISSUE TITLE
[bug] Invalid environment variable error after docker pull

### ISSUE THREAD

**Issue by Flixer** [enricoros/big-agi#187]
After updating the application via `docker pull ghcr.io/enricoros/big-agi:main`, I got the following error:

```
[
  {
  validation: 'url',
  code: 'invalid_string',
  message: 'Invalid url',
  path: [ 'OPENAI_API_HOST' ]
},
  {
  validation: 'url',
  code: 'invalid_string',
  message: 'Invalid url',
  path: [ 'ANTHROPIC_API_HOST' ]
},
  {
  validation: 'url',
  code: 'invalid_string',
  message: 'Invalid url',
  path: [ 'ELEVENLABS_API_HOST' ]
}
]
```

All these values are empty in my .env file.

This results in an empty grey screen when opening the application in my web browser.

**Comment by Flixer** [comment]
I solved the issue. I tried several things, but at the end I think I removing empty lines in my .env was the key to solving this issue.

For example, instead of having
`OPENAI_API_HOST=`
in my .env, which worked in previous versions, I completly removed the line from the .env.

**Comment by enricoros** [comment]
The project has a stricter parsing on the server side now, which will minimize the issues going forward. 
Good job for finding and fixing this. In addition, now it's runtime-supported, and not build-time only, as before.
