### ISSUE TITLE
[BUG] Voice input doesn't stay on

### ISSUE THREAD

**Issue by ramicaza** [enricoros/big-agi#221]
**Describe the bug**
Absolutely love the voice recognition feature! But in a previous version, I would be able to speak, collect my thoughts, then keep speaking. Now whenever there's a pause for a few seconds to think, it ends speech recognition, extremely annoying!  I think this bug was introduced when the 'Voice continuation' feature was added which makes sense because when that mode is enabled, it should automatically determine when to stop 'listening' and send the message. But I'd wager many users (including myself) rarely use 'voice continuation'

Where is it happening?
- All platforms

**To Reproduce**
Use the 'voice input' with voice continuation disabled, say a few things, stop, then see it stop recording.

**Expected behavior**
See above

**Comment by ramicaza** [comment]
I am on Mac. Your proposal makes sense, but if I'm being honest I don't think I would use it because I would likely just switch voice continuation off. I can think of times when I'd take much longer than 5s to collect my thoughts when speaking to it. (maybe i'm just slow 🤠) 

I believe with voice continuation off, it should never stop transcribing unless the user hits the microphone button to explicitly tell it to stop listening. With voice continuation on, your proposal makes perfect sense. To me, I am mainly concerned about the voice continuation off case.

**Comment by enricoros** [comment]
Thanks, I'll prototype this (maybe with a 30s max delay or an "off" option).

The complexity is handling 2 different logics (mobile and desktop behave differently) in all 3 modes (mic is also used for the "Call" function, where I need a timeout signal).

Good inputs.

**Comment by enricoros** [comment]
Added a configurable timeout which works well both for people who want to have quick automatic chats, as well as people that can want to collect thoughts, and something in between.

![image](https://github.com/enricoros/big-agi/assets/32999/0874dd8c-a160-4ac0-acfa-d126f2b3a860)

What do you think?

**Comment by ramicaza** [comment]
Love it!!
Just one minor bug is that you need to refresh the page for the change to take effect.

**Comment by enricoros** [comment]
Fixed it, thanks for reporting @ramicaza!
