### ISSUE TITLE
Rename conversations

### ISSUE THREAD

**Issue by ramicaza** [enricoros/big-AGI#222]
**Why**
The auto-conversation naming is great but can never have a 100% hit rate. I find myself unable to find a lot of conversations because the AI named them improperly and it would be a great feature to be able to manually override the name like in the ChatGPU ui.

**Concise description**
Button next to 'delete' in the conversation history that lets you edit the conversation name.

**Requirements**
None, just a minor UX change

**Comment by enricoros** [comment]
Great idea, added to the roadmap. Would love to have #201 come in place before this.

With #201, we can have more controls on the side pane (pencil to rename), and on the Drawer for mobile (still pencil to rename).

Also a button to "regenerate" the auto title should be added IMO.

**Comment by ramicaza** [comment]
Awesome! really looking forward to this feature.

**Comment by enricoros** [comment]
Landed on Main the new UI. Double clicking on a title will let you rename the conversations.
More to come.
