### ISSUE TITLE
[BUG] Chat titles are incorrect

### ISSUE THREAD

**Issue by peperunas** [enricoros/big-AGI#234]
**Describe the bug**

Where is it happening?
 - Which device [Mobile/Desktop, os version]: Desktop, Ollama backend
 - Which browser: Firefox
 - Which website: Local deployment

**To Reproduce**
Start a chat, read the chat title.

**Screenshots / context**

<img width="1456" alt="image" src="https://github.com/enricoros/big-agi/assets/6033387/8990a146-75c4-431b-97cd-ef3125eeb80a">

The title also have nothing to do with the conversation.

**Comment by enricoros** [comment]
Good job - sounds like prompts for chat titles are llm-dependent, and ollama needs some other sort of encoding/prompting. Remember which model in Ollama? (not necessary for the ticket, just a curiosity)

**Comment by enricoros** [comment]
Note that we are now using the Ollama `/chat` API, which has improved the encoding of the prompt. Now models shall have no issues with titles anymore.

**Comment by enricoros** [comment]
Please let me know if this is correct. I believe this should be the case now.

**Comment by peperunas** [comment]
It works, thank you!

Giulio De Pasquale

PhD Candidate in Program Analysis for Computer Security
King’s College London, Strand Campus

Website: https://pepe.runas.rocks

**Comment by enricoros** [comment]
Nice! Probably the only obscure part is that Chat Titles are generated with the currently selected "functions" model (could be a local llm or cloud llm). Performing the selection of the "function" model is very opaque still.
