### ISSUE TITLE
Adding new branches in a discussion thread

### ISSUE THREAD

**Issue by arbiterFF** [enricoros/big-agi#235]
**The What**
I'd like to be able branch off a discussion at any point in a discussion thread; the branched off discussion should have awareness of its predecessors (and maybe its successors too, but at a lower level of priority?). Prompt engineering will be key to make branching work the way a human brain thinks about it.

**The Why**
Discussions with an AGI should not be just sequential. One should be able to go back and branch a new discussion off of a thread. Often times when I am coding I go back on previous ideas and branch off of them. This then requires a lot of time to instruct the AGI to remember which point in the discussion chain the branch should stem from.

**The How**
I think Slack provides an interesting modal for how discussions can branch. On the downside this could be quite expensive to build as it requires a separate window to slide in.

Microsoft Teams uses a different strategy that I find potentially more attainable short-term and maybe even more usable. The strategy consists in quoting the branch off point at the bottom of the chat.

**Comment by enricoros** [comment]
Added branching:
 - from any message of the chat
 - unified naming with former full-copy (duplicate full chat -> branch)
 - with notifications (#206)
 - use **Ctrl + Alt + Left** / **Right** to switch to the previous window (chat in this case)



![Image](https://github.com/enricoros/big-agi/assets/32999/32ef0623-46ce-47e6-8889-5f685f94399e)
