### ISSUE TITLE
Changes to UI have affected usability

### ISSUE THREAD

**Issue by arbiterFF** [enricoros/big-agi#236]
Some of the recent changes to the UI have slightly affected usability.

For instance in the startup screen, I now have to scroll past the roadmap links to get access to the chat. The "launch button" should always be the most prominent. Suggest splitting the screen in half, moving the launch button to the left and having the updates on the right.

Another thing I noticed is that the API keys are now buried down at the bottom of the UX tab. I find it a little confusing. Also not sure I would say the "Models" are logically part of "UX".

**Comment by enricoros** [comment]
> For instance in the startup screen, I now have to scroll past the roadmap links to get access to the chat. The "launch button" should always be the most prominent. Suggest splitting the screen in half, moving the launch button to the left and having the updates on the right.

Gread suggestions - applying.

**Comment by enricoros** [comment]
Launch Screen (/news): Before | After.

![Image](https://github.com/enricoros/big-agi/assets/32999/cfb52212-259c-4e81-9ebf-78122a55af1b)

**Comment by enricoros** [comment]
> Another thing I noticed is that the API keys are now buried down at the bottom of the UX tab. I find it a little confusing. Also not sure I would say the "Models" are logically part of "UX".

Agree - using the bottom of UX for "Shortcuts" (an explainer), moved LLM Setup to an uncollapsible first spot.

![image](https://github.com/enricoros/big-agi/assets/32999/a5bede3c-0554-4a95-ab99-21053a3c14f5)
