### ISSUE TITLE
[BUG] big-agi doesn't show list of model for Ollama provider

### ISSUE THREAD

**Issue by g1ibby** [enricoros/big-agi#239]
**Describe the bug**
big-agi doesn't show a list of models for Ollama provider.
If I have an ollama model that doesn't contain `PARAMETER` in `Modelfile` big-agi will return `500` code for  request `/api/trpc-edge/llmOllama.listModels`

Here is information that only `FROM` field is required in `Modelfile`: https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#format
so it confirms what in ollama endpoint response `/api/show` only field `modelfile` is requered. 

**To Reproduce**
Add ollama model without `PARAMETER` in `Modelifle` [example](https://ollama.ai/g1ibby/deepseek:6.7b)
```
﻿ollama pull g1ibby/deepseek
```
Check what model doesn't have `PARAMETER`:
```
curl http://localhost:11434/api/show -d '{"name": "deepseek:latest"}' | jq .
```
Trying to get list of ollama models: 
```
curl 'http://localhost:3000/api/trpc-edge/llmOllama.listModels?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22access%22%3A%7B%22dialect%22%3A%22ollama%22%2C%22ollamaHost%22%3A%22http%3A%2F%2F127.0.0.1%3A11434%22%7D%7D%7D%7D' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://localhost:3000/' -H 'content-type: application/json' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```
it returns `500` code.

**Expected behavior**
<img width="725" alt="Screenshot 2023-11-22 at 1 37 02 PM" src="https://github.com/enricoros/big-agi/assets/3687047/b19a238a-8640-4bf1-9a16-c221e8f93f7f">

**Screenshots / context**
<img width="717" alt="Screenshot 2023-11-22 at 1 20 25 PM" src="https://github.com/enricoros/big-agi/assets/3687047/a848cfc3-bb07-43f5-8f18-6c125981e661">

**Comment by enricoros** [comment]
Thanks, closed by #240. Added to the Roadmap and 1.6.0 milestone as well.
