### ISSUE TITLE
Stateful Browser/Code Interpreter container.

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-AGI#247]
Add a docker container to provide a container 'tools' such as browser and code Interpreter.
Note that: Browser is currently used through a Puppeteer API, while there's no orchestration (that I know of) for the code interpreter container.

Requirements:
 - good tools abstraction in place, with auto discovery of capabilities?
 - browser: pre-lunched puppeteer instance?
 - code interpreter: how to define sessions? Chatgpt uses Jupyter notebooks

**Comment by mnm-matin** [comment]
As a smaller stepping stone adding the  'code-interpreter' tool via openai assistant api could be an option.

**Comment by stevenlafl** [comment]
All:

https://github.com/browserless/browserless#docker

**docker-compose.yaml**
```
...
  browserless:
    image: ghcr.io/browserless/chrome
```

**.env**
```
PUPPETEER_WSS_ENDPOINT=ws://browserless:3000
```

![image](https://github.com/enricoros/big-agi/assets/2539092/97d130ca-60e0-4ff7-bf92-5224a9e6196b)

**Comment by enricoros** [comment]
> All, here fits the bill for "pre-launched puppeteer[-compatible] instance" at least:

Great find! Thanks for trying this out.

**Comment by enricoros** [comment]
See #347.

**Comment by enricoros** [comment]
The progress for this will be tracked on #347. Closing this, as Browsing has been implemented (Browserless Docker) and we have a solution in the making that will be explored in the future. Thanks @stevenlafl for the pointer to use Browserless in the first place!
