### ISSUE TITLE
Add options to copy data from markdown tables dynamically to apps such as excel / Export data to excel.

### ISSUE THREAD

**Issue by vaibhavard** [enricoros/big-AGI#250]
**Concise description**
Feature Request - Add options to copy data from markdown tables dynamically to apps such as excel / Export data to excel.

**Example**
![image](https://github.com/enricoros/big-agi/assets/57561743/5c52233b-c3b7-4bc5-a262-d6f2f7afb6e4)

**Methods to accomplish this**
Available API (freemium) to convert markdown to tables:
https://tableconvert.com/markdown-to-excel
https://tableconvert.com/api/#post-/convert/markdown-to-excel

**Comment by enricoros** [comment]
See also #260
