### ISSUE TITLE
New Vendor: Aleph Alpha (Luminous models)

### ISSUE THREAD

**Issue by dhcgn** [enricoros/big-AGI#252]
**Why**
Users will have access to a Large Language Model (LLM) that complies with EU regulations, as Aleph Alpha is headquartered in Germany. Luminous has already been tested by the Innovation Laboratory of the Baden-Württemberg state administration, indicating its potential for widespread adoption in similar sectors. By incorporating Luminous into this open-source project, users will benefit from a user-friendly platform to evaluate and compare its performance with other LLMs.

**Concise description**
Integrate this LLM into the project's suite of available language models. It should be selectable from the graphical user interface (GUI), and users should be able to input their API key for this LLM through the GUI or environment variables, consistent with the implementation for other LLMs.

**Requirements**
Implement a view that allows users to select from various models, similar to the existing functionality for OpenAI's models. 

More Information:
- https://docs.aleph-alpha.com/docs/introduction/luminous/ 
- https://docs.aleph-alpha.com/api/
- https://www.heise.de/news/Control-AI-Aleph-Alpha-Introduces-New-Generation-of-Explainable-AI-Models-9164028.html

**Comment by enricoros** [comment]
From initial investigation, a couple of features are missing now for the common user flows in big-AGI:
1. Output streaming, the https://api.aleph-alpha.com/complete API misses a way to stream text
2. Chat marshalling: the API can 'complete', 'embed', 'explain', 'tokenize', (q&a: deprecated, summarize: deprecated)
3. The "models list" API has been deprecated and no alternative has been provided yet

2023 Nov 30. Reference screenshots for the Docs and Playground:
![image](https://github.com/enricoros/big-agi/assets/32999/90367a3c-ca46-47ba-b2e0-37105358b6d9)
![image](https://github.com/enricoros/big-agi/assets/32999/56d99912-1cb1-4d93-a08d-dad207979418)

Will monitor, for now there's not much we can do, not being able to "chat" with the models. There are some non-chat functions in big-AGI, such as Summarize (Flatten), Titling, Diagram generation (maybe), but we will wait until Aleph Alpha develops their APIs further.

**Comment by enricoros** [comment]
Aleph Alpha does not provide a way to stream. Closing this for the time being, please reopen when the Luminous models support text streaming (a pre-requisite for all llm vendors in big-AGI).
