### ISSUE TITLE
Feature:  http proxy

### ISSUE THREAD

**Issue by crazyStrongboy** [enricoros/big-agi#26]
Can we expose the operation of setting system proxy in the nextjs-chatgpt-app project? Currently, i found that the traffic is not going through the system-level proxy.

**Comment by enricoros** [comment]
Can you give more details about this? (I don't have a system proxy, and I assumed it would be transparent).

What is it, on which OS, and how should it look like on the UI?

**Comment by crazyStrongboy** [comment]
Just like this function :

```
const HttpProxyAgent = require('https-proxy-agent');

const proxy = 'http://127.0.0.1:7890';
const agent = new HttpProxyAgent(proxy);
```

post fetch can use this proxy。Of course, it does not need to be placed in the ui interface, but can be placed in the configuration file

**Comment by enricoros** [comment]
I'm looking into this. There are 2 featches: 1 from the UI to the /pages/api/chat.ts (aka 'frontend to backend' of this app), and another one from the backend to the OpenAI Chat API (https://api.openai.com/v1/chat/completions). 

Do you need both to go through the proxy, or just one of them? If it's just the backend->openAI, I think I have some quick fix for it.

Do you need UI to configure the proxy, or is it okay to have runtime configuration (e.g. if an environment variable, such as HTTPS_PROXY_URL is set)?

**Comment by crazyStrongboy** [comment]
I  want to backend->openAI，now I implement it by calling the interface I wrote myself~~

**Comment by enricoros** [comment]
Do you deploy the backend yourself? If so, I can then update the backend->OpenAI to be like this:

```
// Set up the proxy agent if the environment variable is set
  const proxyAgent = process.env.HTTPS_PROXY ? new HttpsProxyAgent(process.env.HTTPS_PROXY) : null;

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    method: 'POST',
    body: JSON.stringify(streamingPayload),
    agent: proxyAgent, // Add the proxy agent to the fetch options
  });
```

I.e. if you set HTTPS_PROXY (or something similar) when running the App, the request backend->OpenAI shall go through that. What do you think?

**Comment by crazyStrongboy** [comment]
i hava try this yesterday,but failed。But you can try it
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/33116100/227710668-b0b08a93-5b41-42da-9d90-a77536df5571.png">

**Comment by enricoros** [comment]
Totally see the issue. The backend is deployed to the Edge runtime (faster), but node modules such as 'https-proxy-agent' are not supported. Possibly I can just tell to not use the Edge runtime (and instead use a normal backend) when one defines the HTTPS_PROXY env var.
This will ensure that we run a normal backend, and you'll get full nodejs package support.

**Comment by enricoros** [comment]
The code to fix it (in chat.ts), would be:
```typescript
//noinspection JSUnusedGlobalSymbols
export const config = process.env.HTTPS_PROXY ? {} : { runtime: 'edge' };
```

**Comment by crazyStrongboy** [comment]
OK  thank you very much, I'm not very good at nodejs ~

**Comment by crazyStrongboy** [comment]
Can you push this feature to the master

**Comment by enricoros** [comment]
Cannot yet. I tried to just switch the 'runtime' type from 'edge' to 'nodejs', but unfortunately the full handler (and streaming response functions) will need to be rewritten.

**Comment by crazyStrongboy** [comment]
Will it be supported in the future？

**Comment by enricoros** [comment]
I will not write this feature in the near feature, but if someone contributes the code I'll merge the PR.

**Comment by crazyStrongboy** [comment]
> I will not write this feature in the near feature, but if someone contributes the code I'll merge the PR.

Okay, I'll close this issue first

**Comment by epylar** [comment]
This issue should be reopened to prevent duplicates IMO.

**Comment by enricoros** [comment]
Reopening. Please note that at the moment, Vercel Edge functions do not seem compatible with proxy solutions.
Which means to either move to the slower 'node runtime', or not supporting proxy. This is something that should be handled by a fork maybe?

Or looking for creative solutions.
