### ISSUE TITLE
Export Tables as CSV

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-AGI#260]
When a markdown table is rendered, offer a button to export to CSV/XLS, etc.

Requirements:
 - inject a button right after (or top-right corner) to download the table
 - may intercept the Remark/GFM plugins to enable this

Requested by Vaibhav

**Comment by aj47** [comment]
Going to look into implementing this today

**Comment by enricoros** [comment]
Closed by @aj47 with #392.
