### ISSUE TITLE
Enabling password protection will be useful

### ISSUE THREAD

**Issue by vishwa2k** [enricoros/big-agi#269]
When API key is stored and hosted in vercel, there is a chance where anyone can access.

To prevent unauthenticated users from our hosted app it will be good to consider having a website lock.

This password authentication can be enabled in open ai key requested place where password is validated then stored env variable would be used to make calls

Found solution in #177

**Comment by enricoros** [comment]
Thanks @vishwa2k - official support added for HTTP Basic Auth via merging and improving the PR.

Tested and documented on: docs/deploy-authentication.md
