### ISSUE TITLE
[Roadmap] Customizable purposes

### ISSUE THREAD

**Issue by pacoccino** [enricoros/big-AGI#274]
**Why**
"System Purposes" available in this app are fixed and not customizable. They are very close in terms of fonctionnality to OpenAI's GPTs 

**Concise description**

Pre-set purposes are great, but it would be amazing to be able to customize them and create new ones. 
Could be even better if we could share it with other people/create a library/marketplace. 

**Requirements**

- Move the hard-defined [purposes](https://github.com/enricoros/big-AGI/blob/main/src/data.ts) to the database. 
- Create new UI for Creating/Editing... purposes
- (optional) share/import/export a system purpose via public URL/json blob

If this feature is wanted by enough people I can start working on it myself.

**Comment by enricoros** [comment]
Thanks for adding details @pacoccino. This will be done soon. It's a foundational change, but we need it.
#35 will be the main tracker; but not closing this as "duplicate" yet, until I import your requirements.

**Comment by enricoros** [comment]
Quick question about this; is your need specific to the "system prompts" (which essentially are the purposes right now), or would you like greater scope with "personas", which in addition to system prompts will let you customize more: knowledge, tools, voice picture, etc.

**Comment by enricoros** [comment]
Closing due to unresponsiveness from the requester.
