### ISSUE TITLE
Support Gemini (Google Generative AI) Platform

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-AGI#275]
Support the Google generative AI platform and the Gemini models, as documented here:
 - docs: ..
 - login: ...

Requirements:

- [x] Add Gemini  Vendor
- [x] Add Gemini vector icon
- [x] Implement Setup and (transport) Access
- [x] Implement Transport
- [x] Implement Model List mapping (tokens, name, description, etc)
- [x] Implement Streaming endpoint
- [x] Test
- [x] Ship 🚀

**Comment by david-strejc** [comment]
When will this be ready please?
Any estimated time?

**Comment by david-strejc** [comment]
> Support the Google generative AI platform and the Gemini models, as documented here:
> 
> * docs: ..
> * login: ...
> 
> Requirements:
> 
> * [ ]  Add Gemini  Vendor
> * [ ]  Add Gemini vector icon
> * [ ]  Implement Setup and (transport) Access
> * [ ]  Implement Transport
> * [ ]  Implement Model List mapping (tokens, name, description, etc)
> * [ ]  Implement Streaming endpoint
> * [ ]  Test
> * [ ]  Ship 🚀

When will be first version ready?

**Comment by enricoros** [comment]
@david-strejc  This week, ideally tomorrow, at least with the basic features.

**Comment by david-strejc** [comment]
> @david-strejc This week, ideally tomorrow, at least with the basic features.

Many MANY thanks. We are curious what we can do with Gemini.

**Comment by enricoros** [comment]
Support almost complete. Will finish tomorrow.
 - list models; ✅ 
 - immediate generation: ✅ 
 - streaming generation: will be done next
 - image/multi-part input: not ready yet, needs to change all LLM providers - prob preview late this week

![image](https://github.com/enricoros/big-AGI/assets/32999/e1bc9fc6-bcd8-4108-bcf5-bb3abe255fd9)

**Comment by enricoros** [comment]
Code landed for a very good implementation of Gemini.
 - includes streaming, non-streaming, list models
 - includes changeable safety settings
 - includes multipart text conversation building

Next up:
 - ship this in #283, quickly
 - enable the images multi-part pipeline
