### ISSUE TITLE
[Issue] Gemini: Bad Request (400) - User location is not supported for the API use.

### ISSUE THREAD

**Issue by david-strejc** [enricoros/big-AGI#284]
I am getting this error - is there any restriction known for Gemini locations?

**Comment by enricoros** [comment]
Hi, @david-strejc that's correct, Gemini is not yet available everywhere in the world.

However: try it on get.big-agi.com. those servers are on the West Coast of the US, and so you should be fine from everywhere in the world ;)

You can even deploy your own big-AGI on Vercel, and choose to deploy in the US for instance.

Please let me know if this works.

**Comment by david-strejc** [comment]
> Hi, @david-strejc that's correct, Gemini is not yet available everywhere in the world.
> 
> However: try it on get.big-agi.com. those servers are on the West Coast of the US, and so you should be fine from everywhere in the world ;)
> 
> You can even deploy your own big-AGI on Vercel, and choose to deploy in the US for instance.
> 
> Please let me know if this works.

Many thanks - your instance is working when I am using VPN. I don't know if requests are comming from clients browser or backend server or both. Because when I was not using VPN with exit location NY I was getting the same error.

**Comment by david-strejc** [comment]
Am I doing something wrong? 
![image](https://github.com/enricoros/big-AGI/assets/6084451/c39b44cf-8bde-4919-902b-65fcf70cc761)

**Comment by enricoros** [comment]
Haha wow! No, you are using Gemini for sure. They haven't taught it its own identity very well.
It's just HALLUCINATING :D

**Comment by enricoros** [comment]
![image](https://github.com/enricoros/big-AGI/assets/32999/89e2ac6f-7c45-4007-bc26-6b638b545ef2)

**Comment by enricoros** [comment]
Wow, you made quite a discovery. Gemini is the model, but since it's used inside Google Bard, the Google engineers have trained Gemini to think it's "Bard". Wow - incredible! Same results here, as you can see.

**Comment by david-strejc** [comment]
> Wow, you made quite a discovery. Gemini is the model, but since it's used inside Google Bard, the Google engineers have trained Gemini to think it's "Bard". Wow - incredible! Same results here, as you can see.

Nice to know that - so it is "bard" internally and now it is officially "bardgemini" :-))

**Comment by enricoros** [comment]
Forgot to close this one - `bardgemini` is working :D

**Comment by enricoros** [comment]
Forgot to close this one - bardgemini is working :D
