### ISSUE TITLE
Issue: browse did not produce an answer (error: connect ECONNREFUSED 127.0.0.1:4519).

### ISSUE THREAD

**Issue by mrbeandev** [enricoros/big-AGI#285]
**Describe the bug**
i am not able to use /browse option cause i am getting that error `Issue: browse did not produce an answer (error: connect ECONNREFUSED 127.0.0.1:4519).`

Where is it happening?
 - Which device [Mobile/Desktop, os version]: i am using a windows 11 pc
 - Which browser: Chrome V 120.0.6099.110 (Official Build) (64-bit)
 - Which website: https://google.com

**To Reproduce**
1- start chrome with debug mode 
2- use the ws:// it gives in the game http://[127.0.0.1:4519/json/version ( i used 4519 as port for my debug cmd )
3- put that url in big-agi performance tab under browser dropdown.
4- try to chat `/browse google.com`

**Expected behavior**
Issue: browse did not produce an answer (error: connect ECONNREFUSED 127.0.0.1:4519).

**Screenshots / context**
i got the data from chrome's network tab :

`This is the request the BIG-AGI sent :`

```js
fetch("http://localhost:3000/api/trpc-node/browse.fetchPages", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json",
    "sec-ch-ua": "\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Microsoft Edge\";v=\"120\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "http://localhost:3000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"json\":{\"access\":{\"dialect\":\"browse-wss\",\"wssEndpoint\":\"ws://127.0.0.1:4519/devtools/browser/156e0aa1-52bc-4bb5-8564-0e5781aca458\"},\"subjects\":[{\"url\":\"https://google.com\"}],\"screenshot\":null},\"meta\":{\"values\":{\"screenshot\":[\"undefined\"]}}}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```
`the request body in pretty view`
```json
{"json":{"access":{"dialect":"browse-wss","wssEndpoint":"ws://127.0.0.1:4519/devtools/browser/156e0aa1-52bc-4bb5-8564-0e5781aca458"},"subjects":[{"url":"https://google.com"}],"screenshot":null},"meta":{"values":{"screenshot":["undefined"]}}}
```

<hr>

`The Response it got back :`
```json
{
    "result": {
        "data": {
            "json": {
                "pages": [
                    {
                        "url": "https://google.com",
                        "content": "",
                        "error": "connect ECONNREFUSED 127.0.0.1:4519",
                        "stopReason": "error"
                    }
                ]
            }
        }
    }
}
```

**Comment by mrbeandev** [comment]
its fixed , i dont know how 
i download chrome Dev version then i closed everything stopped my ollama , stopped big-agi restarted everything all of sudden it works yuy!!

**Comment by enricoros** [comment]
Nice! You should also look into the Browserless containers. There's a doc for that. Very good results.
