### ISSUE TITLE
Pasting from Excel pastes Image

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-AGI#286]
When pasting from Excel, the Image part takes precedence over the Html (which would be turned into a nice markdown table) or Text

**Comment by Just-A-Pixel** [comment]
I am interested in working on this issue.
May I understand what exactly is being copied from excel?

**Comment by enricoros** [comment]
Are you able to assign this one to yourself?

What happens is that when copying from apps, the clipboard has many formats inside. There's text/html, text/plain,... and image/png or something.

Need to make sure the right format is used, and not a picture.

**Comment by vaibhavard** [comment]
> I am interested in working on this issue. May I understand what exactly is being copied from excel?

Thanks @Just-A-Pixel  for working on this issue. It was raised by me to @enricoros ... 
Do you understand What the problem . I can explain it if you want to :)

**Comment by enricoros** [comment]
Fixed on `main`. **NOTES BELOW**

| Action | Former | Now |
| --- | --- | --- |
| CTRL+V | paste image | Paste table as text |
| Shift+Ctrl+V | paste image | Attach Table as Markdown | 
| "Paste" Button | paste image | Attach Table as Markdown |

**Comment by vaibhavard** [comment]
I appreciate the prompt resolution. The level of developer engagement and the pace of development observed in this GitHub repository are unparalleled in my experience. Thank you.
Shall i Close the issue ✅.

**Comment by enricoros** [comment]
Yep, issue closed (I put "Fixes #286" in the git commit title, which tells GitHub to auto-close. Magic :)
