### ISSUE TITLE
Shortcuts issue on MacOS

### ISSUE THREAD

**Issue by agdfoster** [enricoros/big-AGI#288]
**Describe the bug**
shortcut for retry is described as cmd shift R. I changed my force refresh shortcut so it wouldn't clash but the shortcut appears to be ctrl shift R.

Where is it happening?
 - Which device [mac, desktop, broswer, vercel)
 - Which browser: Arc
 - Which website: vercel

**To Reproduce**
as above

**Expected behavior**
tooltip should say ctrl shift R
Ideally ctrl shift R would refresh the last message by default whether you've clicked on the avatar bubble or not as often you just want to refresh the last message after editing the previous message.

**Comment by agdfoster** [comment]
EDIT - ctrl shift R does refresh the last message by default, apologies

**Comment by enricoros** [comment]
Hi, I recently made a change that should have fixed this: https://github.com/enricoros/big-AGI/blob/aaa3b65cd866ed584b608a574cc4e8fd8abdef21/src/common/components/useGlobalShortcut.ts#L24

Expected:
 - on windows Ctrl + Shift + R
 - on mac Cmd + Shift + R

What is the status? any better way of doing it?

**Comment by enricoros** [comment]
I believe this is closed. Please reopen if this is not correct.
