### ISSUE TITLE
Openrouter.ai rate limit for free tiers

### ISSUE THREAD

**Issue by tmajibon** [enricoros/big-AGI#291]
Openrouter's free tiers are limited to 1 request every 5 seconds. When using ReAct it becomes hit or miss on a free model whether it'll hit the rate limit.

It would be really helpful if this could be implemented internally to automatically delay requests on those models. And for future flexibility this could just be a setting on a model (in case rate limits change or another service implements a rate limit that didn't before).

The most minimal effort version of this would be setting a "delay 5 seconds before sending request on these models", but obviously that's not ideal. The ideal would be an internal timestamp of the last request sent and just adding a wait until that timestamp is 5s old.

**Comment by enricoros** [comment]
Good to know, I think I can deal with this.
How do I determine whether to turn on the rate limiter? (E.g. how do I know if one is Ina free tier?)

**Comment by tmajibon** [comment]
ftr, the "free tier" in openrouter is just that they'll give you $1 of credit before demanding a card (and charging you that balance)

**Comment by enricoros** [comment]
@tmajibon thanks for reporting this. This has been deployed on the main branch, and also on get.big-agi.com.
With the occasion, OpenRouter has been improved, and models have knowledge of free vs non-free. Thanks!

**Comment by shiribailem** [comment]
Thanks! It looks to be working great, I haven't run into any rate limit errors now on those models.
