### ISSUE TITLE
[BUG] Viewport jumps while streaming long ChatGPT responses on iOS

### ISSUE THREAD

**Issue by LennardSchwarz** [enricoros/big-AGI#314]
**Describe the bug**
On iOS browsers, while streaming a ChatGPT response, the window starts jumping when the text streamed is below the visible viewport. This continues even after scrolling manually.

This makes it impossible to read the response while it is being generated. For long GPT-4 answers, this behavior unfortunately makes the app unusable.

Where is it happening?
 - Which device [Mobile, iOS]:
 - Which browser: Safari, Chrome, Firefox
 - Which website: 

**To Reproduce**
On iOS browser, prompt a ChatGPT answer longer than the available viewport. Jumping will start as soon as the viewport is filled up.
I have not tested for other LLMs.

**Expected behavior**
Min expected behavior to fix this bug:
The viewed screen stays fixed after scrolling manually once. The user can then read the text and scroll uninterrupted. This is the behavior of openai.com

Optimal expected behavior:
The viewed screen stays fixed automatically as soon as the streamed response exceeds the viewport. The user has to scroll down automatically, when he wants to see more of the response.

**Screenshots / context**
See attached video.
https://github.com/enricoros/big-AGI/assets/40561724/dee04725-3d22-46a6-a5f3-274ecf7787bf

**Comment by enricoros** [comment]
Hi @LennardSchwarz can you try with the latest version of the app, released yesterday? (1.9.0)

The scrolling framework has been written fully from scratch exactly to address this issue

**Comment by LennardSchwarz** [comment]
Resolved with: https://github.com/enricoros/big-agi/issues/304?utm_source=get.big-agi.com&utm_medium=big-agi
