### ISSUE TITLE
[BUG] Transformation error: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by peperunas** [enricoros/big-AGI#316]
### Device and Browser Information

Device: Macbook M1 Pro

### Describe the bug

Using any Youtube video or text (both modes) when using the Persona feature fails with the error:

`Transformation error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks for the reporting - for sure it's the parser of the LLM provider. One of the upstream models may have changed something in the API?

Which neural network is it using right now? It shows it here, under the **Embodying persona...*:
![image](https://github.com/enricoros/big-AGI/assets/32999/f67e69fd-2aab-4837-99be-7b628db477fc)

Just tried it here:
![image](https://github.com/enricoros/big-AGI/assets/32999/e102d237-87d7-41ac-ae80-ab514ee40b29)

Working for me. Let me know which Vendor/Model you're using for this, and I'll fix it quickly.

**Comment by enricoros** [comment]
A very likely option is that the serverless function got terminated before it could finish its job. I could work this around, if this is the case.

**Comment by peperunas** [comment]
![Screenshot 2023-12-30 at 11 42 15](https://github.com/enricoros/big-AGI/assets/6033387/cc73f84c-3b2e-4997-8aac-b9020fde5798)
![Screenshot 2023-12-30 at 11 42 57](https://github.com/enricoros/big-AGI/assets/6033387/fe093a2a-5522-443d-9cfd-c02fb537abbd)

**Comment by enricoros** [comment]
Thanks I think I know how to solve this, it's definitely a connection to the backend being interrupted (the 2nd, while the 1st worked and produced an output -- this system has 3 LLM calls in a chain).

**Comment by enricoros** [comment]
Hi @peperunas , I've converted the code to use streaming - no more issue with edge functions timeout.
I've verified and it's working now, with the added benefit of instant cancelation of requests in progress.
Thanks for reporting.
