### ISSUE TITLE
Search within conversations and export / delete / open

### ISSUE THREAD

**Issue by syberkitten** [enricoros/big-AGI#324]
**Why**
Searching within previous  conversations

**Concise description**
Be able to search / filter old conversations by typing a search query,  and clicking the one i want to open up.
only those conversations that have more than 1 match show up (rest is filtered out).
list is sorted by the top hits (conversation which has most matches).
ability to export only those (filtered) conversations or delete them.

**Requirements**

**Comment by enricoros** [comment]
Good idea. I'd say that at least basic text search shall be doable quickly, followed by more advanced and eventually embeddings.

**Comment by enricoros** [comment]
@syberkitten, see the new changes by @joriskalz (video below as well).

You can try them on the `main` branch (also on `next.big-agi.com`).

https://github.com/enricoros/big-AGI/assets/1590910/a6b8e172-0726-4b03-a5e5-10cfcb110c68

Please let us know what works, what doesn't, and if this is a good solution to your request.

**Comment by enricoros** [comment]
Hi @syberkitten - this has been implemented. Thanks for requesting. 
Delete works within the Search & Folder, basically what you see is what you delete, very intuitive.
This works great to cleanup chats fast (e.g. filter by "chocolate" and delete all 17).

Thanks @joriskalz for his work in leading the way, I finally connected all the dots.
