### ISSUE TITLE
[HELP] when I run, 'npm run start --port 3000', I get an error:

### ISSUE THREAD

**Issue by AndrewsPanda** [enricoros/big-AGI#333]
### Description

I just tried following the steps to deply manually:

```
git clone https://github.com/enricoros/big-agi.git
cd big-agi
npm install
npm run build
npm run start --port 3000
```

However when I run, 'npm run start --port 3000', I get the following error:

```
> big-agi@1.10.0 start
> next start 3000

 ⨯ Invalid project directory provided, no such directory:
```

### Device and browser

[Ubuntu 22.04.3 LTS]

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by AndrewsPanda** [comment]
My mistake, wrong node.js version

**Comment by enricoros** [comment]
Thanks for trying it and reporting. Happy you solved it already!
