### ISSUE TITLE
Persona Creator: enable user-defined "creation prompts" (flexibility, diversity..)

### ISSUE THREAD

**Issue by younes-io** [enricoros/big-AGI#336]
https://github.com/enricoros/big-AGI/blob/76778c5ab76ab3fcfa07a5cb93954b35ca8aac5e/src/apps/personas/PersonaCreator.tsx#L48

**Why**
Users will gain the ability to tailor the AI's persona to their specific needs and preferences, enhancing the versatility and personalization of the application. The current prompt is overly prescriptive, limiting users to a narrow range of character attributes and stifling creativity.

**Concise description**
A feature that allows users to input custom system prompts for persona creation, thereby enabling the AI to assume a wider array of characters and behaviors as defined by the user. This enhancement should include a user-friendly interface for prompt input and the capability for the AI to interpret and embody the nuances of the user-defined character attributes.

**Requirements**
- Backend logic to process and apply the custom prompts to the AI persona engine
- A set of guidelines or a template to help users craft effective prompts

**Comment by enricoros** [comment]
@younes-io added. See screenshots below (_Advanced: Prompts_)

![image](https://github.com/enricoros/big-AGI/assets/32999/8338399f-392a-4c0e-8e97-2f65141a55fd)

![image](https://github.com/enricoros/big-AGI/assets/32999/c69009cc-8b0c-4137-8924-3d5ef1b1e066)

Let me know if you have more/better ideas on improving this.

**Comment by younes-io** [comment]
That seems like a very good start ! Thank you :D Can't wait to see it deployed 👍🏼

**Comment by enricoros** [comment]
Deployed.
