### ISSUE TITLE
Export Chat to a Markdown file

### ISSUE THREAD

**Issue by vbth** [enricoros/big-agi#337]
### Description

great chat ui. great development. but: where can we find a way to copy the chatbot's answer(s) to the clipboard or export a complete chat into a simple markdown file? unfortunately, in this point the chat ui is inferior to others such as bettergpt in everyday use… or am i missing something here?

### Device and browser

iphone 13 pro, ios 17.2.1, safari 

### Screenshots and more

![IMG_2529](https://github.com/enricoros/big-AGI/assets/13189857/6e645046-f5c7-4e91-8c3b-be65536a431a)
![IMG_2530](https://github.com/enricoros/big-AGI/assets/13189857/d23f7990-d72d-4965-8ed0-41c94bc3276b)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Hi @vbth did you find a way to do this?

**Comment by enricoros** [comment]
Improved the Export dialog, including the new Markdown option:
![image](https://github.com/enricoros/big-AGI/assets/32999/491c5ff0-afa0-47c2-bdd6-799ce6e731f6)
