### ISSUE TITLE
[BUG] Loss of CTRL+SHIFT+V Functionality and Other Issues After Update to 1.10.0

### ISSUE THREAD

**Issue by Satya12-369** [enricoros/big-AGI#345]
### Description

After manually updating the Big AGI application to version 1.10.0, I've encountered a loss of functionality. Specifically, the CTRL+SHIFT+V shortcut, which I frequently use, no longer works. Additionally, there seem to be other features that are missing or not functioning as expected.

Steps to reproduce:
1. Pulled the latest changes from the GitHub repository.
2. Stopped the running Docker containers using `docker-compose down`.
3. Removed the old Docker image using `docker rmi e65805c73b0a`.
4. Updated the `docker-compose.yml` file to use the image tagged with `1.10.0`.
5. Attempted to start the application with the new image using `docker-compose up`.

Expected behavior:
The CTRL+SHIFT+V function should paste the clipboard content as it did before the update, and all other features should operate as before.

Actual behavior:
The CTRL+SHIFT+V function does not respond, and other features appear to be missing or not working correctly.

### Device and browser

Device: PC
OS: Debian 12 bookworm
Browser: Chrome (120.0.6099.216)

### Screenshots and more

![Screenshot from 2024-01-16 09-30-33](https://github.com/enricoros/big-AGI/assets/130947038/84130c58-ddd1-4395-b3c8-b75e3052bc44)

I've also noticed an error in the application logs after starting the updated version. Here's the relevant output:

▲ Next.js 14.0.4
   - Local:        http://localhost:3000

 ✓ Ready in 754ms
Error: aborted
    at connResetException (node:internal/errors:720:14)
    at abortIncoming (node:_http_server:782:17)
    at socketOnClose (node:_http_server:776:3)
    at Socket.emit (node:events:529:35)
    at TCP.<anonymous> (node:net:350:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
  code: 'ECONNRESET'
}

### Willingness to Contribute

- [X] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Hi @Satya12-369 thanks. 

First, for the "ctrl + shift + v" issue, this is happening because Firefox did not support clipboard access (the screenshot is of Firefox, not Chrome).
 - Can you open with Chrome, and test if it works?

**Comment by enricoros** [comment]
2. The "aborted" issue is by nodejs/nextjs when pressing the "stop" button. This is normal and expected, it just says the stream is interrupted and stop producing tokens. This is expected, for instance the Vercel AI SDK does the same exact behavior.

**Comment by Satya12-369** [comment]
sorry for the confusion, still does not work on chrome either

**Comment by Satya12-369** [comment]
Omg youre right!!!

I was browsing it in the Firefox broswer, my b! Now it works! Thank you! Sorry for being stupid! lol 

I appreciate it
