### ISSUE TITLE
Support Together.ai

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-AGI#346]
Add support for Together models; for instance, the new Nous Mixtral is released there first.

**Comment by enricoros** [comment]
Implemented full support, included description (context window) of the latest models, and rate limiting for the free tier.

https://github.com/enricoros/big-AGI/assets/32999/f997c93d-ba36-496e-a4e2-61d13bb416f8

**Comment by enricoros** [comment]
Very fast performance!

https://github.com/enricoros/big-AGI/assets/32999/027e5d77-2adc-4546-910c-67accacac0bf

**Comment by qdrop17** [comment]
Awesome project indeed; unfortunately this feature seems to be broken atm; or there's an incompatibility with the API:

![image](https://github.com/enricoros/big-AGI/assets/42340241/b91d5de7-b6eb-4ee0-881b-5e2c1bb25994)

`Unexpected token 'A', "An error o"... is not valid JSON`

**Comment by enricoros** [comment]
@qdrop17 I just tried it now and it works perfectly here.

![Screenshot_20240130_113543_Chrome.jpg](https://github.com/enricoros/big-AGI/assets/32999/0a7bf381-cdb6-4099-9fe8-0ca27243e038)


Did you self-deploy or used the hosted version?

Anything special related to your API key? (lmk if you are able to provide a temp key for me to try, to check under the same conditions)

**Comment by qdrop17** [comment]
I self-deployed it. But the issue resolved itself when I retried. Maybe a temporary issue with the TogetherAI API.

**Comment by enricoros** [comment]
> I self-deployed it. But the issue resolved itself when I retried. Maybe a temporary issue with the TogetherAI API.

Thanks, very possible.
