### ISSUE TITLE
Unable to load environment variables when running locally

### ISSUE THREAD

**Issue by haopengsong** [enricoros/big-AGI#349]
### Description

Hello, I was unable to load environment variables from .env .
After setting OPENAI_API_KEY in .env, the API Key could not be loaded and I still have to configure the AI Models:
![2024-01-17 200225](https://github.com/enricoros/big-AGI/assets/19417094/6b218d9d-78a6-43d1-ba61-2fd036aa9973)

Also, the' Incorrect API Key' shown in the error message 'AfkWT***************************************PHmn' was not mine.

### Device and browser

WSL2 (Linux Ubuntu) on Windows 11

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
This seems to an incorrect configuration, as this use case is used by many and works. I've tried and tested and it works.

Maybe the OpenAI gets confused?

Please check your env variables in your server (type `env`) because that takes precedence over what's inside the .env file. What OpenAI says is what it receives, and it's all in the user system.

Let us know after you check the env.

**Comment by haopengsong** [comment]
> This seems to an incorrect configuration, as this use case is used by many and works. I've tried and tested and it works.
> 
> Maybe the OpenAI gets confused?
> 
> Please check your env variables in your server (type `env`) because that takes precedence over what's inside the .env file. What OpenAI says is what it receives, and it's all in the user system.
> 
> Let us know after you check the env.

Thanks 1000. I was running the app with my PC whose env was set with an open_ai_api env var which I forgot to delete. After deleting it, I can see the correct loaded from .env. This is great!

Another question, is there a way to suspend the manual model selection? So that model selection will default to the first item in the model list, users can start typing prompts once logged in without having to setup models. I am look at functions such as 'openModelsSetup()'.

**Comment by enricoros** [comment]
Unfortunately not right now. We'd need to add that feature.

**Comment by haopengsong** [comment]
> Unfortunately not right now. We'd need to add that feature. If you want, please open a ticket and I'll be glad to add it to the roadmap. It's low priority compared to other requests, but maybe others will prioritize it.

THanks, just opened a roadmap ticket.
