### ISSUE TITLE
[BUG]why when I use openrouter api，Big-Agi send 2 requests to openrouter every time ?

### ISSUE THREAD

**Issue by firsteyev** [enricoros/big-AGI#362]
### Description

why when I use openrouter api，Big-Agi send 2 requests to openrouter model for every 1 prompt ?
![image](https://github.com/enricoros/big-AGI/assets/128565700/fc7122d4-219a-4f21-bd91-8da78cac9918)

### Device and browser

win10, microsoft edge explorer

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@firsteyev the second request seems the "auto title" of the chat :) you can absolutely turn it off on Preferences > Chat AI > Auto Chat Title: Off.

**Comment by firsteyev** [comment]
> @firsteyev the second request seems the "auto title" of the chat. Shall happen only once, and the 5 output tokens are usual the amount of tokens in a title (around 3 words).
> 
> You can absolutely turn it off on Preferences > Chat AI > Auto Chat Title: Off.
> 
> Please let me know if that's the case, and if so where's the best place to document it.

Thank you! This problem is solved by turning "Auto Chat Title" off.

**Comment by enricoros** [comment]
Great, long use and prosper! :)
