### ISSUE TITLE
[Suggestion]pls add video input models

### ISSUE THREAD

**Issue by allex083** [enricoros/big-AGI#367]
**Why**
Video comprehension is of vast needs comparing to image comprehension. It would be a big advantage if you support it.

**Description**
Add new integration with video-input large models such as video-llava, or other better model if available.

**Requirements**
Pls evaluate all video models in the market and choose the best one to integrate.
Including long video at 500MB+ size and 40mins+ length.

**Comment by enricoros** [comment]
Closed as @allex083 also opened #376
