### ISSUE TITLE
Add Poe.com provider

### ISSUE THREAD

**Issue by johnfelipe** [enricoros/big-AGI#396]
**Why**
will more confortable have all in one UI

**Description**
Like openroute, pls put poe.com compatibility

**Requirements**
really i dont know what need put here....

**Comment by enricoros** [comment]
OpenRourer offers lots of losers with a good api. What does poe offer? Seems like a website/app for bots to me.
What are the benefits to supporting Poe?

**Comment by johnfelipe** [comment]
[image: SNAG-0291.png][image: SNAG-0293.png][image: SNAG-0292.png]
offer claude-2 100k and another interesting....

**Comment by johnfelipe** [comment]
![SNAG-0293](https://github.com/enricoros/big-AGI/assets/428820/cb7ac658-d3de-4113-aea9-e780bbe86a7e)
![SNAG-0292](https://github.com/enricoros/big-AGI/assets/428820/5b9009cc-2291-45d7-be7a-dfc2087332c0)
![SNAG-0291](https://github.com/enricoros/big-AGI/assets/428820/c14114dc-3788-48f9-83b5-ba80c7bc3bec)

offer claude-2 100k and another interesting....

**Comment by johnfelipe** [comment]
yes is possible, im use this: https://github.com/sunner/ChatALL, and have
all POE, free and payed if u have subscription

**Comment by enricoros** [comment]
Thanks. This is based off reverse engineering of the Web Poe client. We don't want to go down that route (which violates poe's terms of service, I'm sure). I'll keep this open until the official API comes out.

**Comment by enricoros** [comment]
Product decision: will not support Poe thought non-official API.

**Comment by johnfelipe** [comment]
I open this because we have poe.com with API now
https://poe.com/es/blog/introducing-the-poe-api
