### ISSUE TITLE
[Roadmap] Persisting Model Visibility Settings & Custom Naming

### ISSUE THREAD

**Issue by eonsonicblue** [enricoros/big-AGI#398]
**Why**
To keep your customized visibility of model and model preset temperature settings and custom names even if you refresh, say, OpenRouter.ai (because currently it returns everything to default if you refresh the model. 

**Description**
Exportable preset model settings?

**Requirements**
Unknown.

**Comment by enricoros** [comment]
Done - note: only enabled on OpenRouter for now. The app does not support tracking user-editing per-flag, so it's hard to say if a model name has changed upstream or by the user.
For now, let's assume the User has control on existing (pre-update) models, and the server has control on the delta.
