### ISSUE TITLE
Vercel One-Click Not Working

### ISSUE THREAD

**Issue by mayurjobanputra** [enricoros/big-AGI#408]
### Description

Tried using the one-click Vercel deployment and it isn't working for some reason.

![image](https://github.com/enricoros/big-AGI/assets/6332663/33ef4046-a86d-4d2b-935f-201f1c4a58be)

### Device and browser

Mac/Chrome

### Screenshots and more

![image](https://github.com/enricoros/big-AGI/assets/6332663/abf04bcb-fde2-4acd-a34f-b4683e15eb7f)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
I can confirm this behavior - not sure if it's a Vercel issue, Github issue, or Big-AGI.

**Comment by enricoros** [comment]
I've applied a change (capitalized a name) - can you try again now @mayurjobanputra

**Comment by mayurjobanputra** [comment]
@enricoros Same result. I'm going to cleanup my account and repos and try again.

**Comment by mayurjobanputra** [comment]
OK. I'm not sure why it failed. I tried to find logs in vercel but don't know where to look and nothing was every deployed. I checked application permissions. Looks fine. What I ended up doing is forking master, and then manually deploying in vercel. I did manage to get the app working. I had to manually set a the openai api key variable during install. 

I would love to see the one-click function work without issue for future non-tech users.

If you need to look at my vercel or github to poke around, I can do a screen share/remote with you.

Let me know.

**Comment by enricoros** [comment]
Big congrats for getting this going. It's definitely meant to be much more pain-free to roll your own vercel deployment.

Do you think the env var step is unnecessary? I can cut that off. It was to show the benefit of an own deployment, some slight customization.

I'm tempted to think it was a Vercel+GitHub issue yesterday (all we do is to have that "button" in big-AGI's readme).

**Comment by mayurjobanputra** [comment]
> Do you think the env var step is unnecessary?

I didn't know I would be able to set that in settings with my user account after login. One thing which SHOULD be a setting during install: allow registration or not.

Most people installing are doing it for their own private use. Registration should be turned off by default except for the user installing the app.

Would be good if the user was asked to create a user account during install/setup.

Right now the app just "runs" after deployment. I was hoping/expecting that when I load the URL the first time, I would be asked for some things like setup admin account, enter key, default LLM, etc. Would be great if that could be done. I would imagine you would need to prevent joe public from running install the first time before the owner. 

If you are open to hearing more, I'm have some ideas how I think the install process should go from start to finish. Lmk if you want some input.

**Comment by enricoros** [comment]
> If you are open to hearing more, I'm have some ideas how I think the install process should go from start to finish. Lmk if you want some input.

Hi, yes, open to hearing more. We just wrote this taking into consideration where we are today:
https://github.com/enricoros/big-AGI/blob/main/docs%2Fcustomizations.md

This shows code or env bar changes, but the absence of a runtime admin panel.

Please share more ideas.

**Comment by mayurjobanputra** [comment]
> Please share more ideas.

I was a Release Engineer for 6 years and Tech Writer for 10 years. I helped "dumb down" very complex installations of banking and enterprise software for Production teams and non-tech users. 

I looked at the page you mentioned. Neat. Not sure I have much opinion on that page as it seems more developer oriented.

Basically, BAGI is missing a few key functionalities that would make it much more useable related to setup/install for the non-tech user:

Post one-click Vercel, the installation should NOT just be ready to use.

Instead, some setup process would be very useful. 

Perhaps...  

1. Generate a 10 digit alphanumeric and email it to the admin (might need to have an SMTP server on stand by for this) or have it show up in Vercel somewhere - logs, etc.
2. Admin then launches installation URL, enters that one-time alphanumerica to finalize install. 
3. During finalization, users can decide/configure a) turn authentication on/off b) allow app to be public/private c) admin user account

I might be spoiled in having this expectation having used WordPress for so many years - the installation is either hands free through web hosts or very straightforward. 

Side note: I deleted my BAGI installation because I couldn't figure out how to setup authentication and don't want joe public to use or see my installation. Unclear how to solve this.

**Comment by enricoros** [comment]
Thanks for the input; I appreciate it. 
Re: authentication, we describe how to have basic auth here: https://github.com/enricoros/big-AGI/blob/main/docs/deploy-authentication.md

Will give it more thought. There is large demand for multi-user configurable installations, but there are also other options for that as free open tools, so we don't feel bad as people can go to different products for it.

Thanks again!

**Comment by enricoros** [comment]
Closing this ticket as the issue resolved

**Comment by mayurjobanputra** [comment]
@enricoros I tried following the authentication instructions but couldn't get it to work. Not even sure what I'm doing wrong tbh. Gave up. If someone can do a video showing how to setup auth for bigagi, that would be great.
