### ISSUE TITLE
Make PlantUML host configurable

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-AGI#415]
Have a environment variable that if set will override the default server.

**Comment by enricoros** [comment]
This is how to pass an env var to the **browser at build time** (I think):

https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

**Comment by enricoros** [comment]
@fredliubojin just saw you made this commit. Lmk if you want me to merge it as-is, or if you want to send a PR (same for me)

**Comment by fredliubojin** [comment]
I've already tested it, so merge it as is should be fine. I was trying to create a PR, but there were too many historic up leveling commits, making a clean PR messy so I couldn't get to finish it.

**Comment by enricoros** [comment]
Thanks for the update, will cherry-pick from your branch right away.
