### ISSUE TITLE
Improvements to the image warning

### ISSUE THREAD

**Issue by dogmatic69** [enricoros/big-AGI#419]
### Description

Generated images have a MASSIVE box on hover that covers all kinds of UI elements (text boxes, buttons, links) that makes it difficult to use.

Perhaps just have a little note that is static at the bottom of the image. No need to include the whole prompt when it's already right there on the page above the image.

### Device and browser

all

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
A static node could be best indeed.

Note that the prompt that is used to generate the image can be different than the one sent by the user: OpenAI by default always rewrites the user prompt (and Big-AGI both shows you the updated prompt, and gives you the option to bypass the rewrite).

**Comment by dogmatic69** [comment]
ah ye, i forgot about the modified prompt. but static under the image is good. 

I noticed it is the worst on a small laptop screen with large image generation. As the image takes nearly the whole page the pop up basically covers whatever is left and avoiding the image is very difficult as it is 80-90% of the screen

**Comment by enricoros** [comment]
@dogmatic69 thanks, added to the roadmap (no eta). Lmk if you have a screenshot to see how bad it is. we have many configuration to support including responsive/pwa on mobile.

**Comment by dogmatic69** [comment]
## No hover

Added some highlighting to point out what I think is important space.

![image](https://github.com/enricoros/big-AGI/assets/94674/d6859269-525b-4902-bd2f-926603a37266)


## Trying to modify last message

cant copy message, cant access button to edit / retry

![image](https://github.com/enricoros/big-AGI/assets/94674/7ceba7a3-b222-4dd5-b63c-3183742e9f97)

## Trying to add new message

Cant see text, cant click send

![image](https://github.com/enricoros/big-AGI/assets/94674/5fcad024-41f0-47b7-93bd-8ce1434a6c4b)

## Mouse movement mockup

Very detailed mockup of how I have to navigate the mouse to be able to safely start a new message.

And in this very situation, I run [synergy](https://symless.com/synergy) and another pc to the right. If the mouse leaves the screen the cursor jumps to centre and when I re-enter this machine I start from the centre again. So the precarious movement along the edge is prone to causing jumping to the middle forcing having to restart the whole dance

![image](https://github.com/enricoros/big-AGI/assets/94674/8671988b-33de-4f01-82fb-496e1c507b48)

**Comment by enricoros** [comment]
Thanks, love this explanation and will figure out a better way - assigned to muself.

**Comment by dogmatic69** [comment]
Another similar one I noticed today. The way this menu opens is also a problem on smaller screens. 

## Large screen is fine

opens up so out the way.

![image](https://github.com/enricoros/big-AGI/assets/94674/228afe61-a826-45a7-a717-3c8dd4a1f3af)

## small screen

opens down over all the other buttons, but worst is that I have to scroll to click "restart". Even if right at the bottom of the page, the menu opens off the page creating a bit more scrollable area.

For reference this screen shot is the very right / bottom edge of the screen. 

![image](https://github.com/enricoros/big-AGI/assets/94674/7c685e05-9b24-407d-9ec1-d6cf9cb58309)
