### ISSUE TITLE
[Roadmap] support for tortoise-tts

### ISSUE THREAD

**Issue by skywalker123p** [enricoros/big-AGI#421]
**Why**
As tortoise-tts can run locally offline, its better to support for privacy reasons.

**Description**
TTS should work using API of https://github.com/neonbjb/tortoise-tts

**Comment by enricoros** [comment]
We don't support TTS python libraries, all of the Big-AGI modules are Services (e.g. need an HTTP address/port).
Can re-open when this becomes a service.
