### ISSUE TITLE
Model knowledge cutoff date

### ISSUE THREAD

**Issue by haopengsong** [enricoros/big-AGI#422]
Is there a need to tune systemMessage for updated gpt models with its most up-to-date date of train data ? 
![image](https://github.com/enricoros/big-AGI/assets/19417094/25232523-c124-4cad-b255-54908d6900da)

I noticed the current setting would replace 'cutoff' with 2023-04 or 2021-09.

THX!

**Comment by enricoros** [comment]
No it's working well already.

**Comment by enricoros** [comment]
This was fixed on v1.13.0. Cutoff is updated (for the default personas at least) automatically. Use the {{Cutoff}} variable in the persona prompt. 

![image](https://github.com/enricoros/big-AGI/assets/32999/8e51c10c-62d6-46c7-8996-0963d92c84b5)

auto-updates with the selected network as you can see from the screenshot.

**Comment by enricoros** [comment]
Oh, wait OPENAI CHANGED IT!

How bizarre - it said March 2023 before. Will update it.

**Comment by haopengsong** [comment]
Great! Seems openai is falling behind their own models...lol

**Comment by enricoros** [comment]
![image](https://github.com/enricoros/big-AGI/assets/32999/facb0643-8241-4704-88c8-128b6ee0bcc1)

Done - landed on `main` already, and will be out for the stable release on v1.14.0. 
Thanks for opening the ticket.

**Comment by haopengsong** [comment]
no problem.
