### ISSUE TITLE
Support for Groq.com

### ISSUE THREAD

**Issue by mayurjobanputra** [enricoros/big-AGI#427]
**Why**
There is a new AI I just discovered called Groq at https://groq.com. I tried it and it performs well but is missing several core features: saving chats and more. 

**Description**
Enable ability to configure a groq API key. See more at https://wow.groq.com/

**Requirements**
Enable ability to configure a groq API key. See more at https://wow.groq.com/

**Comment by enricoros** [comment]
@mayurjobanputra incredible performance, enables new use cases.

I've applied for an API key, but nothing yet. I'd love to add formal support. If you get Access, can you give me a temp key to add the integration until mine comes?

**Comment by enricoros** [comment]
@mayurjobanputra still haven't gotten an API key. Adding support for it shall be trivial.

**Comment by Honkychunkymonkey** [comment]
If you need it, there's https://console.groq.com/docs/quickstart

**Comment by mayurjobanputra** [comment]
I applied. If I do get access, will certainly set you up with a key for testing @enricoros

**Comment by mayurjobanputra** [comment]
This is what they said. So I guess you can get access right away @enricoros 

Enter in your email and the magic link sent to your inbox will provide you access.

**Comment by enricoros** [comment]
Thanks a bunch @mayurjobanputra I'll get to it today and use it for as little as adding support

**Comment by enricoros** [comment]
Closed with @Penagwin's great contribution. Shipping today.

**Comment by enricoros** [comment]
![image](https://github.com/enricoros/big-AGI/assets/32999/761a8a9b-c5d9-4c6c-aa23-423939403896)
