### ISSUE TITLE
[BUG] chat history seems not respected

### ISSUE THREAD

**Issue by happy15** [enricoros/big-AGI#428]
### Description

model: mistral 7b-instruct-v0.2-q5_K_M

steps:
1. paste "https://netflixtechblog.com/introducing-safetest-a-novel-approach-to-front-end-testing-37f9f88c152d" in chat, after page loaded, hit enter. 
2. chat returns a summary paragraph regarding the blog text at the url above.
3. enter "summarize the text with bullet points like I am 5".
4. chat returns "ChatGPT is a big computer program that talks and learns, made by OpenAI.
It's called GPT-4 model.
Knowledge it has learned is from before 2021.
Now it's 2024, two years after its knowledge cut off.
I am supposed to explain things in a way a 5 year old can understand.
ChatGPT summarizes text by making points like this:
Summarize: A long text about something.
Bullet points: Like dots on a list.
Understand easily: Simple words and ideas.
Explain: Make things clear and simple."

expected:
it will still summarize the blog text at the url.

possible problem:
is it because the context window exceeded and the head of the history is truncated? if so, how to setup context window for the model?

### Device and browser

mbp 14
microsoft edge

### Screenshots and more

<img width="839" alt="image" src="https://github.com/enricoros/big-AGI/assets/983570/7a1e7b29-2ee7-47b7-bbfe-62717606c484">

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by happy15** [comment]
mistral 7b seems to support context window as long as 32k, as per info from lm studio when loading mistral 7b.

**Comment by enricoros** [comment]
@happy15 who's your provider for that model? Many support misteal. Seems to be a bad encoding of the chat messages.

**Comment by enricoros** [comment]
From the second message I read this is with LMStudio?

1. Context Window of 32k: The problem is that LMStudio does not report any information about the context window to the API, and with so many models we cannot hardcode all the context length for models. --> cannot solve it without LMStudio collaboration (e.g. OpenRouter, Google and others tell the context window)

2. The Chat issue: this is on the LMStudio front. Big-AGI encodes the Chat correctly (as you see it split in different messages) and passes it down to the framework (LMStudio, which then encodes it for llama.cpp or other low level engines). So there's nothing really we can do from our side other than passing  a well formed chat to the Chat API. -> Not Big-AGI issue/fix.

Leaning towards closing this unless there are more information

**Comment by happy15** [comment]
> @happy15 who's your provider for that model? Many support Mistral. Seems to be a bad encoding of the chat messages.

for usage in big-AGI: `ollama pull mistral:7b-instruct-q5_K_M`

for lm studio: TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q5_K_M.gguf

**Comment by happy15** [comment]
> From the second message I read this is with LMStudio?
> 
> 1. Context Window of 32k: The problem is that LMStudio does not report any information about the context window to the API, and with so many models we cannot hardcode all the context length for models. --> cannot solve it without LMStudio collaboration (e.g. OpenRouter, Google and others tell the context window)
> 2. The Chat issue: this is on the LMStudio front. Big-AGI encodes the Chat correctly (as you see it split in different messages) and passes it down to the framework (LMStudio, which then encodes it for llama.cpp or other low level engines). So there's nothing really we can do from our side other than passing  a well formed chat to the Chat API. -> Not Big-AGI issue/fix.
> 
> Leaning towards closing this unless there are more information

My apology for not express it clearly.

When using big-AGI, I use ollama as api server. 

I mentioned LM Studio just to talk about the context window length of 32k.

**Comment by happy15** [comment]
Additional info fyi: with ollama-webui it knows to summarize the text at the link.
<img width="831" alt="image" src="https://github.com/enricoros/big-AGI/assets/983570/62e4ad39-aed9-4cc6-ad74-396ad11fcf30">

**Comment by happy15** [comment]
BTW, big-AGI is super cool that lets me do ReAct with local model and web search very easily.

**Comment by happy15** [comment]
turns out I can setup context length with modelfile on ollama side. 

close for now.

Thanks for the response and great work.

**Comment by enricoros** [comment]
> BTW, big-AGI is super cool that lets me do ReAct with local model and web search very easily.

Great job to be able to configure it correctly. We added a new docs/README.md for overall documentation, if you need it.
