### ISSUE TITLE
Feature request: Allow to hide models from the list in a single click

### ISSUE THREAD

**Issue by academo** [enricoros/big-AGI#430]
**Why**
Ease of use

**Description**
In the model list, one can easily hide a model with a single click by clicking the eye icon.
![image](https://github.com/enricoros/big-AGI/assets/227916/90830349-915c-45ac-8596-e7a3860b94f6)

But hiding the model requires many extra clicks:, Click settings, click the visibility toggle, click Close.

![image](https://github.com/enricoros/big-AGI/assets/227916/c0b5d52e-8ccc-40b7-8cdf-145cd6a6566a)

Could we have the eye icon to toggle visibility in a single click? 

This becomes rather tiresome with providers such as openrouter that provide a great amount of models and constantly update them.

Thanks!

**Comment by enricoros** [comment]
Thanks for asking! Done.
![image](https://github.com/enricoros/big-AGI/assets/32999/1333cf71-2815-4ef9-91e3-363539ab5db4)

**Comment by academo** [comment]
Thanks so much for implementing it <3
