### ISSUE TITLE
LocalAI Model Gallery Doesn't Work

### ISSUE THREAD

**Issue by oldmanjk** [enricoros/big-AGI#431]
### Description

Follow instructions to setup LocalAI Model Gallery. Click "Gallery Admin."
Available Models List: (truncated)
[ { "code": "invalid_type", "expected": "string", "received": "undefined", "path": [ 63, "license" ]...

Command Prompt: curl http://localhost:8080/models/available: (truncated)
..."}},"files":[{"filename":"xwin-mlewd-13b-v0.2.Q8_0.gguf","sha256":"","uri":"https://huggingface.co/TheBloke/Xwin-MLewd-13B-v0.2-...

### Device and browser

Windows 11 Latest Brave

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by oldmanjk** [comment]
It works with the official gallery, but not the community one

**Comment by enricoros** [comment]
Closing as a fix has been provided.
