### ISSUE TITLE
[BUG] Is text generation stream?

### ISSUE THREAD

**Issue by null8tr** [enricoros/big-AGI#433]
### Description

I use an endpoint and my endpoint has enabled stream response but it seems don't stream in big-AGI

### Device and browser

Desktop Windows 11 

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Hi @null8tr - it is streaming. Are you using an OpenAI-compatible source? What's your endpoint model server?
Need more info to help here.

**Comment by enricoros** [comment]
Please provide more details, as we don't know where to start. Streaming works.

**Comment by enricoros** [comment]
Closing as no detail and no folow-up.

**Comment by null8tr** [comment]
I'm sorry I didn't receive notification for your issue
Yes this is an OpenAI future that allows streaming tokens like this
1 . Hello
2 . Hello how 
3 . Hello how can 
4 . Hello how can I
and...
you can check their example in [OpenAi example](https://cookbook.openai.com/examples/how_to_stream_completions)

by the way sorry for the late answer
