### ISSUE TITLE
Best Debug setup.

### ISSUE THREAD

**Issue by haopengsong** [enricoros/big-AGI#461]
Please help with how to setup a debug environments for big-agi. I have been trying with the debug setup introduced in nextjs official doc: https://nextjs.org/docs/pages/building-your-application/configuring/debugging
But it does not seem to work ...

**Comment by enricoros** [comment]
Hi @haopengsong can you copy and paste a screenshot of where it's not working? To understand your environment and what step is not being successful.

**Comment by haopengsong** [comment]
Sure,
Following is the screenshot of the launch.json file I used. Here I copied the exactly same file from official nextjs doc (https://nextjs.org/docs/pages/building-your-application/configuring/debugging):
![image](https://github.com/enricoros/big-AGI/assets/19417094/df420fba-8a28-437b-abfd-0516b6b33092)

Second, is the step that right before I start debugging. Here I put a breakpoint and about to start debug the server side :
![image](https://github.com/enricoros/big-AGI/assets/19417094/d9a39bd1-5285-4aa3-9402-2bb11658329e)

After click start debugging, nothing happens ...

**Comment by haopengsong** [comment]
This is what happened after I run 'npm run dev' which start the server on localhost:3000. I can oberserve the debugger attached to the port but the program won't stop at the breakpoint where it supposed to ...
![image](https://github.com/enricoros/big-AGI/assets/19417094/780ca20c-9996-47f9-b319-a2eb8811a295)

**Comment by haopengsong** [comment]
This is what happened after I run 'npm run dev' which start the server on localhost:3000. I can oberserve the debugger attached to the port but the program won't stop at the breakpoint where it supposed to ...
![image](https://github.com/enricoros/big-AGI/assets/19417094/780ca20c-9996-47f9-b319-a2eb8811a295)

**Comment by enricoros** [comment]
Got it, thanks for the details. For the frontend side, while running npm run dev, I use Chrome to debug.

I place the breakpoints in Chrome > Debug > the Sources tab. Magically all the source code shows up.

Or I go more commonly with old school `console.log(...)` which will output either to the browser console (frontend) or terminal console (backend code).

The Composet file is Frontend (or Client-side), and I debug it in Chrome looking at the terminal. Haven't yet tried connecting the IDE to Chrome for frontend. The IDE I use in big AGI is InteliJ WebStorm.

**Comment by haopengsong** [comment]
Wow, thanks for the detailed guidance. Seems like I misunderstood the difference between front & back-end code.
I will definitely try Chrome to debug the frontend!
Cheers.

**Comment by enricoros** [comment]
Hi haopengsong, let me know how your adventure is going and watch out for the new 1.15.0 release of big AGI which is just around the corner!
