### ISSUE TITLE
(error: Invalid wss:// endpoint).

### ISSUE THREAD

**Issue by MichaMaGit** [enricoros/big-AGI#462]
Hi, 

I am playing around and stepped on this error: (error: Invalid wss:// endpoint).

In LM Studio I am able to post Web Links and the LLM will read and summarize the Website.

In Big-AGI I am getting this error if I write" /browse www...."
(error: Invalid wss:// endpoint).

If I post a link just in the chatbox the llm says it "can't browse the internet".

Am I doing something wrong?

Thx a lot.

**Comment by MichaMaGit** [comment]
Sorry I used GPT 3.5 turbo, that's why it was not working.
So now is my question, why is it working with a local model but not with GPT 3.5 ?

**Comment by enricoros** [comment]
Hi @MichaMaGit it seems like you want to browse the web, but big agi needs the connection to a browser. See the browser docs, and the setting in Preferences > Tools for the wss address.

**Comment by MichaMaGit** [comment]
Thank you! So if I am using local models, I don't need this? Only with API Models?

**Comment by enricoros** [comment]
Hi @MichaMaGit. Take a look at the configuration of the feature (Preferences > Tools > Browse) and it explains where in big AGI the features being used.

The most reliable way is to "Paste" a URL on the text editor in hig-AGI, and you  should see the page being downloaded and attached to the message. This way, when it's sent to the LLM, then model does not be aware of any tool or configuration, the page is simply already attached to your message.
