### ISSUE TITLE
Chat name and icons misaligned in Zen appareance [BUG]

### ISSUE THREAD

**Issue by jpalbert** [enricoros/big-AGI#465]
### Description

Hi,

When the Zen appareance mode is selected, the chat name and the icons are not aligned anymore in the left menu. Now that the avatar is missing, the icons should also align to the left, as shown below :

![image](https://github.com/enricoros/big-AGI/assets/7884120/391a115a-95cd-4a11-ad48-1eaefadf311d)

It seems the span class shown below should be removed in Zen mode :

![image](https://github.com/enricoros/big-AGI/assets/7884120/452b23a3-cca7-4631-9b3f-a789fc0d1cf0)

However, the result is slighly off because of the first icon padding :

![image](https://github.com/enricoros/big-AGI/assets/7884120/0191b634-857d-4c07-9364-1e27d9ce1be4)

I would suggest also adding a left-padding of 6px to the title above : 

![image](https://github.com/enricoros/big-AGI/assets/7884120/5554f380-15a2-4d22-ae4d-16dddc7a3198)

Hope this helps. Great tool.

### Device and browser

Windows 10, Chrome Browser.

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks very much for reporting @jpalbert . This issue has been fixed on the main branch and will be released in the coming days as part of 1.15.0

**Comment by enricoros** [comment]
Ready for release.
