### ISSUE TITLE
BEAM - feature thread

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-AGI#470]
Big-AGI 1.15.0 introduces BEAM, a chat mode that lets you **find a better answer**. Beam is a user-centered multi-model chat that allows the user to select the best responses, and fuse them together in different ways.

Released on March 28, 2024 to the first round of Early Adopters.

Released publicly on April 1, 2024.

---
Former description from the "Best-of N" naming:
In this mode, the assistant will generate N (2..10) completions, which will be shown to the user on a modal popup dialog. When all of them are done, they become active and scrollable. At this point either the user can select one of them to append to the conversation that started it all, or can use a "Merge"function specifying the criteria.

- [x] initiate from the "Retry" or "Restart from here" menu options
- [x] also initiate as a special "Mode" for the Chat
- [x] **Beams** (aka alternate responses) are generated from: Chat up to that point, submitted N times in parallel
- [x] **Merge** happens by applying: [merge system, prompt, optional initial system prompt, history, last user message, N alternatives, merge user message]

**Comment by younes-io** [comment]
While this is an interesting feature, why is the chat configured on Beam mode _by default_?
I use the keyboard a lot, and having everytime to click on `chat` with the mouse is a bit annoying.. it would be nice if users could have the flexibility to setup their own preference. Personally, I'd use Beam very rarely, so I would prefer to have the Chat button set up by default when I hit "Enter"
