### ISSUE TITLE
No option to change model [BUG]

### ISSUE THREAD

**Issue by yesbhautik** [enricoros/big-AGI#471]
### Description

There is no any option to change AI model in chat screen

### Device and browser

I'm currently using Google Chrome beta enterprise mode on Windows 11 pro.

### Screenshots and more

![image](https://github.com/enricoros/big-AGI/assets/63995315/eb23414d-a8b5-482e-9403-fcaef55257cc)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Hi @yesbhautik this is because in Preferences> Experimental there's the "Chat Title" experiment on 😅

**Comment by enricoros** [comment]
Closing - this was a user option - and removed from the UI, so users cannot make that mistake again.
