### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yesbhautik** [enricoros/big-AGI#472]
It will be great if you implement multi-user environment with user management on admin panel, along with SaaS.
Give option to provide API key in environment, so i want to share this platform then other guys don’t have to insert API key stuff or i don’t have to share the API.

**Comment by enricoros** [comment]
Hi @yesbhautik. I just completed #436. This means that if you set the API keys on the backend, your Frontend (s) will auto configure models for your users.

Here's how you can deploy:
 - set API keys in the backend env vars
 - follow the instructions on https://github.com/enricoros/big-AGI/blob/main/docs/deploy-authentication.md to set a common password protection (env vars + a file rename)

This won't be a multi user environment, will be a same install used by multiple users.
In the future we'll have a fully managed multi user install, but requires a larger spec and work than what's in this ticket, hence I'm closing for now.

**Comment by yesbhautik** [comment]
What will be the environment vars name?
