### ISSUE TITLE
[Roadmap] Include in the Midori AI Subsystem

### ISSUE THREAD

**Issue by lunamidori5** [enricoros/big-AGI#477]
**Why**
The subsystem already supports Ollama and LocalAI, letting users manage their installs really easy, why not add Big AGI to the manager so they can try out what they like?

**Description**
A okay or not okay to add Big AGI to the subsystem

**Requirements**
Your blessing <3
- [ ] ...

Thank you all so much for your hard work!

**Comment by enricoros** [comment]
Where can I learn more about the _subsystem_?

**Comment by lunamidori5** [comment]
@enricoros https://io.midori-ai.xyz/subsystem/manager/ and https://io.midori-ai.xyz/subsystem/ (the pages on using each backend together are not done yet as I want to get the manager out of beta before making those)

**Comment by lunamidori5** [comment]
@enricoros may I go ahead and get started on adding support for installing Big AGI in the subsystem <3

**Comment by enricoros** [comment]
You are blessed! @lunamidori5 . Please let me know of the features that will make the integration more seamless.

**Comment by lunamidori5** [comment]
(looks like your readme.md for now)

**Comment by enricoros** [comment]
Perfect. You should use the container tagged "latest" which with now = v1.15.0, released yesterday. (avg frequency of releases: 3-4weeks)

The other container, "development" will have the newest features and be updated frequently, but does not guarantee stability at all.

Yes, when you're done I'll create a dedicated markdown for how to install/deploy. Surprisingly something I don't have now.

**Comment by lunamidori5** [comment]
@enricoros where is the servers config saved to so it can be backed up when updating the docker compose? (sorry for the bother)

**Comment by enricoros** [comment]
On the server side it's all env vars, there is no other state :) all the user chat, user config, UI state is on the client side.

**Comment by lunamidori5** [comment]
@enricoros Cool!! Thank you, I should have a PR ready tonight!

**Comment by enricoros** [comment]
Then I better be ready too

**Comment by lunamidori5** [comment]
@enricoros  ![chrome_ANEqJd89rk](https://github.com/enricoros/big-AGI/assets/118759930/77539c9b-4193-4be7-bb83-1024e5c7c529)

**Comment by enricoros** [comment]
Oh nice! With env vars configuration, it will auto discover models from local model servers. If you want to glue up the system you can set those (they must be set when starting the container). UX will be great.

**Comment by lunamidori5** [comment]
> Oh nice! With env vars configuration, it will auto discover models from local model servers. If you want to glue up the system you can set those (they must be set when starting the container). UX will be great.

Ill have to make a backend program to do that, but it should be easy to do.

**Comment by lunamidori5** [comment]
Closing Issue for now! thank you again! - @enricoros

**Comment by enricoros** [comment]
My pleasure! I'll extract the deployment section into its own .md and publish it on the big AGI website as well.
