### ISSUE TITLE
Anthropic API not working

### ISSUE THREAD

**Issue by babulee** [enricoros/big-AGI#485]
### Description

I am trying Anthropic API Claude 3 Opus as of April 2024, and I get the following
[Service Issue] Anthropic: Forbidden (403) · {"error":{"type":"forbidden","message":"Request not allowed"}}

OpenAI Chatgpt API works fine

I also tried OpenRounter, and OpenRounter's ChatGPT and Mistral also works.

However when I try OpenRounter's Anthropic Claude 3 Opus, I get the following
[OpenAI Issue] { "error": { "type": "forbidden", "message": "Request not allowed" } }

### Device and browser

Windows 10, Edge Browser

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@babulee I cannot reproduce - since you experience the same in OpenRouter, I think it was Anthropic servers: https://status.anthropic.com/
Please let me know if you still experience the issue (post a screenshot).

**Comment by babulee** [comment]
I got it figured out.  Since I am outside of USA.  Verified it is working with VPN.
