### ISSUE TITLE
Edit LLM response

### ISSUE THREAD

**Issue by alkampfergit** [enricoros/big-AGI#486]
**Why**
Scenario: I'm asking LLM to generate code that does something, I usually proceed in steps, ask for something, then proceed asking to generate other method etc. The LLM generate code that I like but sometimes I like to change something. (how a property is named, how the method is named, or minimal stuff).

**Description**
In such a scenario I edit the response of the LLM, Changing generated code to adhere to my desire. Then I proceed with a next question to further proceed generating other part of the class /Code. Now the LLM will proceed based on modified code.

**Requirements**
I simply need to be able to edit not only my question but also generated step of LLM answer.

**Comment by enricoros** [comment]
Hi @alkampfergit this should already be working. Either double click the LLM answer or choose Edit from the message menu. It's very important to be able to edit indeed. Please let me know if you are able to make it work.

**Comment by enricoros** [comment]
@alkampfergit please comment if this is now working for you, or otherwise we can close this safely.

**Comment by alkampfergit** [comment]
Apologize, I completely missed the double click! It works like a charm.
