### ISSUE TITLE
[BUG] unable to confgure Azure OpenAI from server config

### ISSUE THREAD

**Issue by dogmatic69** [enricoros/big-AGI#491]
### Description

Running in docker with compose, want to be able to configure with ENV vars as per OpenAI. 

### Device and browser

n/a

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@dogmatic69 please add some details, Azure OpenAI works with 2 env vars - please see the guide.

**Comment by dogmatic69** [comment]
I found it now by going through the source code. 

The docs make no mention of the vars, only the UI config. https://big-agi.com/docs/config-azure-openai

**Comment by enricoros** [comment]
https://big-agi.com/docs/environment-variables <- you're right it's hidden.
https://github.com/enricoros/big-AGI/blob/main/docs/environment-variables.md
