### ISSUE TITLE
[Roadmap] Change Microphone Input

### ISSUE THREAD

**Issue by liquidsnakeblue** [enricoros/big-AGI#501]
**Why**
Users will be able to change the input microphone

**Description**
Just need to be able to select the input source for the microphone.  I have many different inputs and even though I set the default browser input correctly, the call feature still does not detect any input from my voice.

**Requirements**
If you can, Please break-down the changes use cases, UX, technology, architecture, etc.
- [ ] ...

**Comment by enricoros** [comment]
Unfortunately the Web Speech API which is what we use for the speech to text, does not support changing the input.

I've looked into the spec of the API and open bags and I couldn't find any information nor any technical way of doing this.

To enable switching of the microphone we will need to have a full in house media Pipeline and using stt voice transcription services. That functionality may come but it's way broader than just changing the input.
