### ISSUE TITLE
Please specify mount path in the docker compose file

### ISSUE THREAD

**Issue by arsaboo** [enricoros/big-AGI#510]
### Description

not really a bug, but it will be nice to specify a mount path to save settings for ease of portability. The current [docker-compose](https://github.com/enricoros/big-AGI/blob/main/docker-compose.yaml) does not specify any file mounts. 

### Device and browser

Mac Studio

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
The project does not keep any state on the backend. State (configuration) is provided to the backend via env variables, but the bulk of the state (chats, configurations) is saved on the frontend itself (the browser itself, via IndexedDB).
