### ISSUE TITLE
[BUG] Custom Endpoint URL in Anthropic Configuration Rejects Non-standard API Key Formats

### ISSUE THREAD

**Issue by ZoinktheBoink** [enricoros/big-AGI#511]
### Description

**Issue Summary:**

When inputting a custom endpoint URL into the API Host field within the Anthropic configuration, the system fails to accept API keys unless they adhere to the specific format of `sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`. Any deviation from this format results in the API key being highlighted in red and subsequently not passed through the request to the API host. This limitation hinders the use of reverse proxies that require custom API key formats.

**Steps to Reproduce:**

1. Access the Anthropic configuration settings.
2. Enter a custom endpoint URL into the API Host field.
3. Attempt to input an API key that does not follow the `sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` format.
4. Observe that the input is highlighted in red and the system does not accept it.

**Expected Behaviour:**
The system should allow for the input and acceptance of custom API keys in various formats, especially when using a custom endpoint URL, to accommodate the use of reverse proxies and other integration needs.

**Actual Behaviour:**
Only API keys following the specific `sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` format are accepted. Any other format is rejected, which is indicated by the input field highlighting the key in red and preventing it from being used in requests to the API host.

**Request:**
Please remove the API key format requirement when a custom API endpoint is used in the Anthropic configuration.

### Device and browser

Windows 11, Firefox.

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks @ZoinktheBoink . If you submit a quick patch removing the 'sk-..' check from the Anthropic key (start from anthropic.vendor.ts, or anthropic.router.ts) I'll merge it.
