### ISSUE TITLE
Vllm completions/chat api connectivity [Roadmap]

### ISSUE THREAD

**Issue by Playerrrrr** [enricoros/big-AGI#512]
**Why**
i like running localhost port  local llms via VLLM, would be awesome if I had an UI to interact and continue my work as llm dev on big-agi, instead of running my own custom python scripts. If there is a way to connect them, please enlighten me, thank you in advance!

**Comment by enricoros** [comment]
Can you explain me more, I don't understand the workflow. Have you tried using a generic "OpenAI" model vendor, with advanced options to set host and port?
