### ISSUE TITLE
[Roadmap] Ollama python API - enable 'format' parameter use

### ISSUE THREAD

**Issue by sealad886** [enricoros/big-AGI#515]
**Why**
Models with Ollama tend to do better overall when the `format='json'`  argument is set in the  API request. We can update the prompt, and certain  models will do quite well with that. But would be good to have this available to configure, especially with hwo I've been using Beam lately to evaluate a number of models serially on various tasks. 

**Description**
The only supported value for `format` currently is `format='json'` within the API call ([see here](https://github.com/ollama/ollama/blob/main/docs/api.md) for that note), but sounds like it may be extended in the future?

Request is to have a drop-down menu on this config page perr model:
<img width="750" alt="image" src="https://github.com/enricoros/big-AGI/assets/155285242/315cbcaf-760e-448c-b630-3bf632f636fb">
This one-item drop-down menu could be extended in the future. Default value = None. Alt-text = "Set to the format that  you are also requesting explicitly in your system or user prompt."
Functionally would only be used to populate that API parameter.

**Requirements**
- Ollama config page UI change
- Save new field to config files
- Update Ollama API call

No change to how output is processed, necesasarily.

**Comment by sealad886** [comment]
Sorry, [this](https://github.com/ollama/ollama/blob/main/docs/api.md) note in the API parameters documentation is actually where it says `json` is the onlly supported value now.

**Comment by enricoros** [comment]
Thanks @sealad886 this has been implemented as a "Source" parameter, meaning you'll toggle it once for this source and not the model.

To turn it on:
![image](https://github.com/enricoros/big-AGI/assets/32999/af77441d-558b-4188-b601-4d408c3efc0e)

Then you can use it:
![image](https://github.com/enricoros/big-AGI/assets/32999/ae99e7ca-a6e6-4b22-bcc4-a7cf5d9360d6)
