### ISSUE TITLE
Soft-wrap code blocks

### ISSUE THREAD

**Issue by afanjul** [enricoros/big-AGI#517]
Hi, is there any way to soft-wrap code blocks in the AI responses? If the response contains a code block the code (html or whatever) is pretty difficult to read because the lines are not wrapped. Could you please provide a way to activate the code blocks soft-wrap?

thanks

**Comment by enricoros** [comment]
![image](https://github.com/enricoros/big-AGI/assets/32999/a43047f8-fc14-4530-90d4-5969eeedb383)

**Comment by afanjul** [comment]
Many thanks @enricoros  :-)
Is it possible to make an option to make it permanent by default? Its a bit tedious to keep pressing all the time... 
<img width="851" alt="Screenshot 2024-05-09 at 15 08 25" src="https://github.com/enricoros/big-AGI/assets/2046424/9c53ab36-0ce2-40ed-8ea9-6e059c07d2df">

**Comment by enricoros** [comment]
What I can do is to remember its (pressed /unpressed) state and sync it across objects.
So every code block will be wrapped once you press it, basically. (And same if you unpress)

Would that work? (I'm always looking to Remove UI and options)

**Comment by afanjul** [comment]
Would be much better, and i'm with you with the "too much options" filosofy ... thanks

**Comment by enricoros** [comment]
> Would be much better, and i'm with you with the "too much options" filosofy ... thanks

Done, will be out in `main` tomorrow as source, and will be live in the next stable version.
