### ISSUE TITLE
[BUG] Dark-mode doesn't properly work for graphs

### ISSUE THREAD

**Issue by Yardanico** [enricoros/big-AGI#520]
### Description

Thanks a lot for the frontend! I really like it and I think it'll the frontend I'll be use for my personal usage in the future. In the past I've tried Koala (BetterGPT fork), LobeChat, LibreChat, and some others.

Here's about the small bug itself:

If you use the diagram tool or ask the LLM to draw a diagram right in the chat, with dark mode you won't be able to see some of the diagram features.

Here's an example diagram:
```
@startuml
node "TypeScript Framework" as ts

node "C++ Engine Kernel" as cpp
node "TS Engine Kernel" as tsk

node "Native Platforms\niOS, Android, Mac, Windows, etc." as native
node "Web Platforms" as web  
node "Mini-Game Platforms" as minigame

ts --> cpp
ts --> tsk
cpp --> native
tsk --> web
tsk --> minigame
@enduml
```

I think there are two solutions for this problem - either find/create and use PlantUML/Mermaid dark themes, or always force light mode for diagrams (or via a toggle)

### Device and browser

Arch Linux, latest Brave Browser, user-agent "Mozilla/5.0 (X11; U; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6295.214 Safari/537.36", same happens on Android 14 with Chrome.

### Screenshots and more

Dark:
![image](https://github.com/enricoros/big-AGI/assets/21169548/0c6aacbc-6b9f-4d46-9d6f-9f175fcd7bf5)
![image](https://github.com/enricoros/big-AGI/assets/21169548/0de90923-a00d-4a2d-b0e3-c3079b8c11e2)

Light:
![image](https://github.com/enricoros/big-AGI/assets/21169548/36f38bd7-7f12-42c4-a1d0-6d98e42a5610)
![image](https://github.com/enricoros/big-AGI/assets/21169548/9c9f2027-98cb-4ff1-b499-8a0c63a4b967)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks. This code is SVG, produced by the PlantUML rendering service (plantUML.com).
I'll look into fixing this by having a lighter background (on charts only) when in Dark mode.

**Comment by enricoros** [comment]
This is how a diagram in PlantUML or MermaidJS will look like now.
![image](https://github.com/enricoros/big-AGI/assets/32999/cd8db2eb-0423-4d74-aa9f-1ef37f58a857)

This is deployed to `main` which will become the next stable release within a week. You can either build and run it today from main, or wait until it's out.

**Comment by enricoros** [comment]
Thanks a bunch for providing the details.

**Comment by Yardanico** [comment]
Thanks a lot for a quick fix!
