### ISSUE TITLE
[BUG] Chatting without having entered any API key fails silently

### ISSUE THREAD

**Issue by dandv** [enricoros/big-AGI#523]
### Description

1. Build and run locally
2. Escape the dialog to enter an API key
3. Send a chat text

Note how no response is returned (predictably), but the UI doesn't complain in any way that there's no API key. So the user might've spent time crafting a complex prompt, and after sending it, the prompt will be lost. There is no history of it.

This makes for a disappointing first-time new user experience

### Device and browser

Firefox 123 on Linux

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks @dandv very true.
