### ISSUE TITLE
[BUG] Imprecise "check usage" link for configuring Anthropic API key

### ISSUE THREAD

**Issue by dandv** [enricoros/big-AGI#524]
### Description

When configuring the Anthropic API key, what exactly is the "check usage" link supposed to do? Can there be a more precise wording?

### Device and browser

Firefox 123 on Linux

### Screenshots and more

![image](https://github.com/enricoros/big-AGI/assets/33569/394790a4-6734-45c7-81bd-a456512909fc)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks for the report @dandv, fixed. Points to a more specific URL which shows usage:
![image](https://github.com/enricoros/big-AGI/assets/32999/f3e6321d-7295-402e-8823-a3b6d6191183)
