### ISSUE TITLE
Issue: Oops! It looks like we had trouble understanding the Model. Could you please try again?

### ISSUE THREAD

**Issue by nomopo45** [enricoros/big-AGI#528]
### Description

After asking a question with Beam x2 feature, I asked for a guided Merge, it will generate checklist and then during the criteria selection phase it will pop this error : 
"Issue: Oops! It looks like we had trouble understanding the Model. Could you please try again?"
And yes i did retry but always end up to this issue

Not sure how can i do to resolve this issue ? i'm willing to try by myself if i'm guided a little.

I'm using LMStudio with llama3 8b.

<img width="1145" alt="image" src="https://github.com/enricoros/big-AGI/assets/67263927/4702610b-b043-46d9-b6bd-72e0f91de333">

PS: thanks for this amazing tool

### Device and browser

macbook m1 pro 16gb

### Screenshots and more

<img width="1143" alt="image" src="https://github.com/enricoros/big-AGI/assets/67263927/8b3ef81b-809b-4e0f-9ec6-bff5fe83c127">

### Willingness to Contribute

- [X] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
> Not sure how can i do to resolve this issue ? i'm willing to try by myself if i'm guided a little.

Hi, this is because the parser for a guided (checklist) expects a checklist from the model. A checklist in markdown is a "- [ ] ..." list of lines.

Update: as I was finding the code to point you to, I found the error. I already predicted this case, but the trigger had a bug. Solution below.
