### ISSUE TITLE
Prompt responses [BUG]

### ISSUE THREAD

**Issue by MrBenzWorld** [enricoros/big-AGI#532]
### Description

there is a bug in latest update.  response is not clean.
![Screenshot 2024-05-10 002120](https://github.com/enricoros/big-AGI/assets/113277019/63087ab6-f1ad-4b6c-a11c-4547bd40caaf)

### Device and browser

windows 11 
chrome , Yandex 

### Screenshots and more

![2](https://github.com/enricoros/big-AGI/assets/113277019/45ab4739-c895-4f60-aa4c-baa87edb311a)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
This is not on the big-AGI side but it's a bug in the local model vendor.
The "chat" encoding from the chat API to the model is not working well.
Which vendor is this?
You can try different models of the same vendors, or different local vendors.

**Comment by MrBenzWorld** [comment]
Same problem with LM studio , Ollama . 

It was working fine with previous version.

**Comment by enricoros** [comment]
![image](https://github.com/enricoros/big-AGI/assets/32999/bb32fe33-a888-4590-9c1d-c9279d836489)
