### ISSUE TITLE
Allow directly delete a chat without confirmation

### ISSUE THREAD

**Issue by afanjul** [enricoros/big-AGI#537]
**Why**
Its a bit tedious to need 2 clicks to delete a chat

**Description**
When the user click the remove chat button with "Alt" or "Shift" pressed (whatever you prefer) delete without confirmation. It's what is doing other UIs. 

**Requirements**
Very easy :-D , just add a key modificator to the click to change the behaviour a bit

**Comment by enricoros** [comment]
Done - @afanjul do you deploy via code (`main` branch) or wait for the changes to be stable on big-agi.com?
