### ISSUE TITLE
[BUG] Prodia doesn't generate images

### ISSUE THREAD

**Issue by sparking-meteor** [enricoros/big-AGI#543]
### Description

Prodia returns an error when trying to generate an image using any of it's models

### Device and browser

Device: Android 13, Firefox 125

### Screenshots and more

![Screenshot_20240513_171724_Iceraven](https://github.com/enricoros/big-AGI/assets/143058963/a042195a-0c65-41d7-9d24-3517cd3688df)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@sparking-meteor this is a message that is returned from the prodia server - probably needs to add money to the account; just tested and it works here. Closing because it's not a big-AGI bug.
