### ISSUE TITLE
[BUG] "AI Personas Creator" -> From Text shows the same fields as from YouTube

### ISSUE THREAD

**Issue by dandv** [enricoros/big-AGI#548]
### Description

When switching to "From Text", the same Advanced Prompt fields are kept from YouTube. This may be a little confusing.

A simple fix would be to change "Analyze the transcript" to "Analyze the transcript/text".

### Device and browser

All

### Screenshots and more

![image](https://github.com/enricoros/big-AGI/assets/33569/89be9340-ad8b-47b8-8448-ae8d8c91d93d)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Great - this is a no-brainer, shall be done quickly.

**Comment by enricoros** [comment]
Fixed by #575 by @therippa
