### ISSUE TITLE
[BUG] constant unrequested call to {diagram model}

### ISSUE THREAD

**Issue by kaptainkangaroo** [enricoros/big-AGI#560]
### Description

Issue: an unrequested call to the secondary diagram model is made every time the chat button is clicked. resulting in extra charges

Step 1. Configure Model settings with OpenRouter account. 
Step 2. set Auto diagram to include "Phind: CodeLlama 34B v2" (see screenshot)
Step 3. start a session and click chat button , (in a session with ANY LLM model)
Step 4. See the extra charge on the activity page on OpenRouter (https://openrouter.ai/activity?page=1) 

<img width="1250" alt="image" src="https://github.com/enricoros/big-AGI/assets/72245146/fca729c9-5cdc-425a-9de6-ad7290b2a96f">

screenshot:
shows an additional call to "Phind: CodeLlama 34B v2"  even when the free version of mistral is called
<img width="1040" alt="image" src="https://github.com/enricoros/big-AGI/assets/72245146/8b66600b-4b6b-4f5e-8e41-5c471690869b">

### Device and browser

m1 Macbook Air, OS: 13.6.6 (22G630)
Chrome: Version 125.0.6422.142 (Official Build) (arm64)
BIG AGI: 1.16.1

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@kaptainkangaroo please try the following:

1. Check if the call is from the Auto-Title:
 - [ ] switch off auto-title for chats
 - [ ] check if the secondary call (with a different model) is made
![image](https://github.com/enricoros/big-AGI/assets/32999/6f656879-08aa-4b7f-93ba-0175e26d2269)

2. Make sure the "Auto Diagrams" is off as well.
 - [ ] with both auto-title and auto-diagrams off, please check the network requests
 - [ ] if there's a second network request, look into the prompt (example in chrome below)
 
![image](https://github.com/enricoros/big-AGI/assets/32999/203a1fdf-c96c-4f5b-83ce-42848658e8f5)

Let me know once you're done.

**Comment by enricoros** [comment]
Closed for inactivity, and support has been provided.
