### ISSUE TITLE
[BUG] Webapp functionality all gone?

### ISSUE THREAD

**Issue by lactoseintolerant** [enricoros/big-AGI#561]
### Description

I use get.big-agi.com. Something happened today and I can only use OpenAI models. The options for the other models vanished. The settings all vanished along with their icons. The site reverted to some barebones implementation.

### Device and browser

Android Chrome

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Hi @lactoseintolerant - we just updated to the latest 1.16.2, released 15 min ago. Sorry for the downtime, it's now all operational.
