### ISSUE TITLE
[BUG]Error updating Gemini model: invalid_enum_value

### ISSUE THREAD

**Issue by dovegq** [enricoros/big-AGI#565]
### Description

I'm encountering an error when attempting to update the Gemini model. I'm receiving the following error message:

[ { "received": "createCachedContent", "code": "invalid_enum_value", "options": [ "countMessageTokens", "countTextTokens", "countTokens", "createTunedModel", "createTunedTextModel", "embedContent", "embedText", "generateAnswer", "generateContent", "generateMessage", "generateText" ], "path": [ "models", 11, "supportedGenerationMethods", 2 ], "message": "Invalid enum value. Expected 'countMessageTokens' | 'countTextTokens' | 'countTokens' | 'createTunedModel' | 'createTunedTextModel' | 'embedContent' | 'embedText' | 'generateAnswer' | 'generateContent' | 'generateMessage' | 'generateText', received 'createCachedContent'" } ]
 

### Device and browser

windows11 + Chrome 125.0.6422.142  +  big-AGI 1.16.0 

### Screenshots and more

![image](https://github.com/enricoros/big-AGI/assets/23547122/81a7a06d-e45e-4810-97b9-4b882b0fa90e)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks for reporting @dovegq, you were very quick to find out. Google added a new capability to the Gemini model family and we have a strict protocol checker. Sorry for any inconvenience.

**Comment by dhcgn** [comment]
Is there a workaround for this issue? I just added the `GEMINI_API_KEY` and didn't load the models in the past.

**Comment by scragz** [comment]
I'm getting this now.
