### ISSUE TITLE
[BUG] - Double clicking to edit a prompt or response often opens the wrong one.

### ISSUE THREAD

**Issue by agdfoster** [enricoros/big-AGI#568]
### Description

This has been happening for quite a long time. January at least.
Double click to edit the bot / user message (I do this a lot)
A different message opens in editor.
I can't see a pattern for when it does / doesn't happen yet.

Other symptoms of potentially same bug:
In the editor for a prompt, (not the input), often typing or pasting doesn't do anything.
Generally exiting the prompt editor and coming back in fixes it.
Often I need to go to a different part of the same prompt, add some new lines and a few characters, then delete them, then it will let me freely edit again

### Device and browser

macOS Sonoma 14.3.0

### Screenshots and more

Will try to catch it!

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
I also edit a lot the history @agdfoster . There's a full new rewrite of the message editing in the making. Already landed on the feature-multipart branch, but don't use it yet, it's in big flux.

**Comment by enricoros** [comment]
Closing as the new editing experience will bring this for free.
