### ISSUE TITLE
[BUG] Quick fix: cannot find Claude's newest model `claude-3-5-sonnet-20240620` in model list

### ISSUE THREAD

**Issue by tranhoangnguyen03** [enricoros/big-AGI#569]
### Description

In Anthropic service, only Claude 3 Sonnet is `anthropic-claude-3-sonnet-20240229` whereas `claude-3-5-sonnet-20240620` is now available.

### Device and browser

Desktop & Mobile alike

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by tranhoangnguyen03** [comment]
Sorry, I missed the latest release changelogs. 

Great job, guys!

**Comment by DoS007** [comment]
@tranhoangnguyen03 I did a `git pull` in my existing program path to update and started after that the program and clicked in the GUI on "Models <refresh symbol>", but still no 3.5 sonnet?

**Comment by DoS007** [comment]
@tranhoangnguyen03 You're right, it's the old version. I don't understand. I also did `git pull --force` and other things, and it didn't update.

Deleting and downloading anew solved it. But is that normal to always delete the program and download it anew. Maybe this has something to do via starting `start /MIN npx next start --port 3000`.

Just to check: When you update, you always just do `git pull` and it works for you?

**Comment by dandv** [comment]
I've also git pulled, and `git log` shows the last commit from 3 days ago, but still don't see `claude-3-5-sonnet@20240620` or the 1.16.3 version. `/news` shows 1.6 from 2 months ago.

```
$ git log
commit e3fce43e6246e3c51f37b97f247c703e3d87e4b8 (HEAD -> main, origin/main, origin/HEAD)
Merge: 5c1a7d48 aa7959a9
Author: Enrico Ros <enrico.ros@gmail.com>
Date:   Tue Jun 25 02:15:25 2024 -0700
```
