### ISSUE TITLE
[Roadmap]

### ISSUE THREAD

**Issue by andreicozma1** [enricoros/big-AGI#573]
**Why**
This feature would allow users to seamlessly reference specific parts of previous messages without having to manually type out or copy-paste the text. It enhances user experience by making interactions smoother and more efficient.

**Description**
Introduce a quote reply feature similar to the feature in the ChatGPT interface.

- Allows quickly referencing specific parts of previous messages 
- Provides the assistant with more specific context about what the user is referencing
- Removes the need to manually describe specific parts or to copy-paste and format the message as a quote-reply prompt. 
- Makes user-assistant interactions more smooth and user efficient

**Requirements**

- **Basic UI/UX**:
  - As the users select text from previous assistant replies using the cursor, a button with a quote icon will pop up next to the selected text. 
  - Clicking this will activate the prompt injection into the next message sent to the assistant.
  - The user's textbox will display a truncated version of this snippet at the top of the textbox, indicating that they are using the quote reply feature. An X button allows the user to cancel the quote reply.

- **Additional Considerations**:
  - In the message history, quote replies could retain the additional display at the top of the user's message showing that it was a quote reply.
  - All previous messages in the thread that contain quotes will continue inject that quote into the prompt for the corresponding message when it is sent to the API (quotes stored directly as strings along with the message).
  - An X button on the quote portion of a thread message allows optionally removing quotes if so desired.

**Comment by enricoros** [comment]
Yep, we got this done already :) not on the main branch yet

**Comment by andreicozma1** [comment]
> Yep, we got this done already :) not on the main branch yet

whoops, sorry, I didn't find it when I searched the issues originally; I found it now. That's great, can't wait for it!
Is it the `feature-multipart` branch?

**Comment by enricoros** [comment]
Correct, but don't use the branch in production yet - it's a MASSIVE update to data structures, LLMS substrate, etc. There may be data losses on existing installations and it will throw exceptions on multi-part fragments (will be ready really soon tho)

**Comment by enricoros** [comment]
It will look like this:
![image](https://github.com/enricoros/big-AGI/assets/32999/f931b906-809c-42ef-96fe-556dd0d874b9)

**Comment by enricoros** [comment]
Closed as duplicate.
