### ISSUE TITLE
Serving the app from subdirectory (mydomain.com/big-AGI) not working

### ISSUE THREAD

**Issue by nick-harder** [enricoros/big-AGI#579]
## Issue
Unable to serve the app from a subdirectory (mydomain.com/big-AGI). App doesn't load or route correctly.

## Setup
- Docker image of big-AGI under port 4000
- Nginx reverse proxy to the port 4000
- Desired URL: mydomain.com/big-AGI

## Questions
1. Any special considerations for Docker/Nginx setup?
2. How to handle routing and asset loading in this scenario?
3. Is there maybe a basePath variable to enable serving under a subdirectory?

Additional details available upon request. Thanks for any help!

**Comment by enricoros** [comment]
Sorry, not planned and won't be done unless someone wants to contribute the code. 

This is complex and will require to modify the ways that we access the API backend (tRPC) and the NextJS routing.

Maybe some magic in the nginx proxy could rewrite some URLs but I'm not sure.
