### ISSUE TITLE
Set server preference default

### ISSUE THREAD

**Issue by SamKr** [enricoros/big-AGI#584]
### Description

Hi @enricoros, for starters thanks for your continuous work on this - I still use it daily and it's been great ever since I started using it :)

I have a small question: is it possible to set a preference as the server's default? Specifically this one:

![image](https://github.com/enricoros/big-AGI/assets/1439763/fda3576a-cfb0-4750-8e0b-e77763ad563d)

I found that edit mode can confuse people when they just want to copy something, for instance source code. So I advise them to just turn it off, but it'd be even easier if I could just set it as default. 

I went through the docs, but didn't quite find what I needed. Is it possible at all, or could you point me in the right direction?

Thanks again :)

### Device and browser

Not applicable

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@SamKr in your case, do you have access to the code? It's a single line of code change to flip the default of that variable. Or how else could the defaults be changed?

**Comment by SamKr** [comment]
I use docker compose, but if it's a matter of changing a file inside the container then that's fine. Perhaps .env variables to set config defaults would be nice for a future version?

**Comment by enricoros** [comment]
@SamKr yes, for now please edit this line: https://github.com/enricoros/big-AGI/blob/0b3b4a6417bd5e65cf19b54994bc1a4ecc35edf5/src/common/state/store-ui.ts#L26

We have >30 env vars so it's becoming unmanageable. 

For now please go with editing that 1 line of code, may require pretty much the same effort.
