### ISSUE TITLE
[Roadmap] Suggestion for obtaining available Anthropic models.

### ISSUE THREAD

**Issue by dandv** [enricoros/big-AGI#585]
**Why**
Currently Anthropic models are [hard-coded](https://github.com/enricoros/big-AGI/blob/main/src/modules/llms/server/anthropic/anthropic.router.ts#L14), and users have to download a new version of big-AGI to be able to use newer models.

**Description**
1. The AWS Bedrock SDK provides an en endpoint to obtain the list of Anthropic models.
2. Please upvote the [feature request to provide a model list](https://github.com/anthropics/anthropic-sdk-typescript/issues/458). Hopefully more demand may help the Anthropic team consider implementing this in the future.

**Comment by dandv** [comment]
In the meantime Anthropic has added an [endpoint to list all models](https://github.com/anthropics/anthropic-sdk-typescript/issues/458#issuecomment-2562150850).

**Comment by enricoros** [comment]
@dandv already implemented a couple of days ago and landed on v2-dev :)

I'm using that endpoint, plus adding details that the endpoint doesn't provide (prices, context sizes, features, etc.

I've also made sure that the second Anthropic releases a new model, it's available to be used in the app (by assuming the largest features set).

**Comment by dandv** [comment]
Excellent, thank you @enricoros!
