### ISSUE TITLE
Three dots in zen appearence mode

### ISSUE THREAD

**Issue by nick-harder** [enricoros/big-AGI#586]
Thanks a lot for such a nice app! I foudn myself prefering the zen mode, but somehow I cannot figure out how to access the three dots functionaly for individual messages when in zen mode? Is this a bug or desired behavior? Or maybe I am simply missing something.

**Comment by enricoros** [comment]
@nick-harder very good point. I also prefer the cleaner Zen, but as you found out, the 3 dots menu is just not there. I don't know where to put it - any ideas?

**Comment by nick-harder** [comment]
@enricoros my initial idea would be to simply display the three dots in place of the avatar in the zen mode. We could also make the three dots semi-transparent and when hovering solid, and also reduce the distances so everything is still "Zen" but with all the functionality.
<img width="1085" alt="image" src="https://github.com/enricoros/big-AGI/assets/56074305/6c3812ea-ca0c-4f53-bfbf-6478b427261f">
<img width="687" alt="image" src="https://github.com/enricoros/big-AGI/assets/56074305/9e5c0b55-8c2e-433b-9546-3defcfebc63a">

**Comment by enricoros** [comment]
Good idea. I will do this.

**Comment by enricoros** [comment]
@nick-harder done in the experimental branch. Will be out for everyone in a few weeks.

Desktop:
![image](https://github.com/enricoros/big-AGI/assets/32999/308e780e-400c-457a-8caa-616c80eaee05)

Mobile:
![image](https://github.com/enricoros/big-AGI/assets/32999/deb9cd35-f197-4242-92f0-bcdc892c9944)
