### ISSUE TITLE
[BUG] streaming doesnt work for me

### ISSUE THREAD

**Issue by admin-dsai** [enricoros/big-AGI#587]
### Description

Streaming is not working for us. No matter the operating system or browser.

[Screencast from 08.07.2024 11:38:19.webm](https://github.com/enricoros/big-AGI/assets/52493935/49bd92f3-d57f-4765-936b-35a7a0fb4997)

### Device and browser

Video was taken on Ubuntu 22 with Google Chrome

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by nick-harder** [comment]
@admin-dsai if you are serving the app using a proxy such as nginx, you need to adjust the config for it, I had this issue as well. Please let me know if this is the case for you

**Comment by nick-harder** [comment]
@tddsai If you use nginx reverse proxy, you need to add the following code to the configuration file right in the /location

```
# No caching, support streaming output
proxy_cache off;  # Turn off caching
proxy_buffering off;  # Turn off proxy buffering
chunked_transfer_encoding on;  # Turn on chunked transfer encoding
tcp_nopush on;  # Turn on TCP NOPUSH option, disable Nagle algorithm
tcp_nodelay on;  # Turn on TCP NODELAY option, disable delay ACK algorithm
keepalive_timeout 300;  # Set keep-alive timeout to 65 seconds
```

@enricoros maybe we could add this somewhere in the documentation? I bet many people face this problem

**Comment by tddsai** [comment]
@nick-harder thank you very much, it works very great

**Comment by enricoros** [comment]
Thanks @nick-harder, @tddsai done
