### ISSUE TITLE
Project should have an identifiable name

### ISSUE THREAD

**Issue by koganei** [enricoros/big-agi#6]
Should this project have a more identifiable name than "NextJS ChatGPT App"?

GPT-4 suggested these:

1. "ChatGPT Nexus”. The term “Nexus” reflects the convergence of diverse features and customizations, while maintaining an academic tone. This name highlights the central role of ChatGPT as the core technology and suggests a hub where developers, scientists, and other users can collaborate and explore the app’s diverse functionalities.

2. "ChatGPT Synergy": "Synergy" suggests the interaction and cooperation of multiple components to create a combined effect greater than the sum of their individual effects. This name accentuates the app's integrated nature, where various features like chat streaming, code highlighting, and code execution work together to provide an enhanced user experience.

3. "ChatGPT Codex": A "Codex" is an ancient manuscript that typically contains multiple texts. This name alludes to the project's rich collection of features and presets, signifying a comprehensive resource for developers and users to access and contribute to. Moreover, it conveys an academic tone, making it suitable for a project with diverse user types, including scientists and executives.

And then we can make the title of the application reflect that name, along with the current model from the settings (if my PR gets merged).

**Comment by enricoros** [comment]
The current name sounds like a template, it's probably better to change it, indeed :)
Those are good options. Let's see if people want to use it and have more useful functionality (right now I kept it simple to serve as basis for other's code and learning), then we can definitely rename it

**Comment by enricoros** [comment]
@koganei @fredliu @peperunas @typpo - ideas on the project rename?
Any values we should hammer on? Openness, innovation, taking the lead, creating something great?

**Comment by peperunas** [comment]
Personally, I would focus on privacy as the UI runs entirely client-side - and I'd make this one of the main advantages of this project.

**Comment by enricoros** [comment]
Baby steps. See #77 for a possible icon. Candidate name? 'structure'.

**Comment by enricoros** [comment]
More names - like any?
 - Astria
 - Astramind
 - Astutia
 - Brainify
 - Clevera
 - Eurekly
 - Enlightera
 - Structure

**Comment by enricoros** [comment]
Project rename successful
