### ISSUE TITLE
[Question] Why not call API directly from frontend?

### ISSUE THREAD

**Issue by powellnorma** [enricoros/big-AGI#609]
I really like the UI + UX of this project so far. Was just wondering why the API-Keys are sent to the server, instead of the frontend calling the Backends directly? Are there some AI Backends that require this (e.g. because of missing CORS Headers etc.)?

**Comment by enricoros** [comment]
@powellnorma you got it right. It's mostly a CORS issue. Most backend services will not work with a direct connection. It's an unfortunate reality to deal with and forces a duplication (or more) in the network stack, so we need the client<>server<>AI service communication unfortunately. This also opens the door to future server smarts (e.g. caching, or images storage)
