### ISSUE TITLE
YouTube Transcriber: Error fetching transcript. Please try again. 

### ISSUE THREAD

**Issue by BlaisePx** [enricoros/big-AGI#617]
### Description

Getting this error no matter the link I try.

Like this one: https://youtu.be/o0A9M5wHBA4

Worked wonderfully two days ago. 

### Device and browser

Android, Chrome Browser

Windows 10, Chrome Browser 

### Screenshots and more

![Screenshot_20240811-045526](https://github.com/user-attachments/assets/f0808301-0b4f-4edc-91d2-e54cf8f01937)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
It's working for me now, I wonder what happened, it could have been a network issue. I think I have an improved input message in big AGI 2.

Talking about big AGI 2, wanna see an exciting YouTube feature? Pasting the URLs gets the transcription into any chat :)

![Screenshot_20240812_022224_Chrome](https://github.com/user-attachments/assets/c5acc4fa-0e54-4c8f-9021-53975f165f6d)

**Comment by enricoros** [comment]
@BlaisePx please let me know if this stops working again - we need to catch the servers while they have the issue.
Which website/branch is this on?
In the meantime I've added better instrumentation.

**Comment by BlaisePx** [comment]
It started working for me (sometimes), not sure why. I am so looking forward to version 2.

Thank you!

**Comment by tfriedel** [comment]
I have adguard running and this prevented the transcript fetching. After I disabled it once it would work even after I re-enabled adguard, probably because of caching.

**Comment by enricoros** [comment]
Thanks @tfriedel , I recently fixed an issue where not all YouTube links were transcribed correctly, but "youtu.be/" links were broken. This issue was present especially on mobile. If this is still happening, can you share the link? It's possible that YouTube may be throttling the server that's accessing the transcript (the vercel edge server for the free hosted version, if you don't deploy locally).

**Comment by enricoros** [comment]
![image](https://github.com/user-attachments/assets/a56e4898-ac8c-4565-8441-d55e44c6832f)

Found a possible culprit.
