### ISSUE TITLE
[BUG] Small bug when using big-AGI 2

### ISSUE THREAD

**Issue by hourianto** [enricoros/big-AGI#618]
### Description

Decided to try to use big-AGI 2 a bit (hopefully you'll release it soon enough), and there's this small thing. For some reason, big-AGI is sending the system prompt for Anthropic as an array. It works with the official API, but it's undocumented, so I think it would be better to make it align to what the official API says. Other implementations (like proxies for LLMs) rely on the official API docs, so I stumbled upon an issue of a proxy not supporting this way of sending the system prompt. 

Basically, big-AGI sends this:
```json
{"max_tokens":4096,"model":"claude-3-5-sonnet-20240620","system":[{"type":"text","text":"You are an AI conversation titles assistant who specializes in creating expressive yet few-words chat titles."}], "messages":REDACTED,"stream":false,"temperature":0.5}
```

Notice how `system` is an array of entities. If you check the official docs at https://docs.anthropic.com/en/api/messages, they specify that the `system` parameter should be just a `string`. I guess this is also a bug on their end (for not properly verifying the inputs), but I think big-AGI should just stick to the default way :)
![image](https://github.com/user-attachments/assets/fdaf4f0a-a048-4eb7-9585-28fbc07364ab)

Proposed fix: make big-AGI 2 always pass the system prompt as a simple `string` to Anthropic's Messages API, not as an array.

### Device and browser

Arch Linux, Brave version: 1.68.137 Chromium: 127.0.6533.100

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@hourianto great find. I'm unsure whether to fix or not, as there are reasons for this. Big-AGI ad had the Network stack fully rewritten to enable multimodality, function calling, and more.

It's not an Anthropic bug for not verifying, it's how Anthropic truly works under the scenes. It's the way to enable images in system prompts and multi-part (image, text, audio, text) system prompt. The docs don't document this Yet, but they will soon.

For this specific case I guess I can add a hot fix and downcast the multi-part system message to a single text string, but in the future we'll be back to the current behavior. Again: our new network stack (AIX) is awesome.

**Comment by hourianto** [comment]
@enricoros okay then, fair enough, as long as Anthropic docs update it soon enough. But I've also tested passing `image` message type to the system prompt in an array, and the API tells me:
```
{"type":"error","error":{"type":"invalid_request_error","message":"system.0.type: Input should be 'text'"}}
```

Or do you have some inside knowledge from Anthropic that they will allow this in the future?

**Comment by enricoros** [comment]
@hourianto I'll do the down mix in a bit, it's 5 minutes.

What's important is that I keep the high level representation (multi-part, etc.) before the down mix into a single text.

Here, this is the official Anthropic python SDK:
https://github.com/anthropics/anthropic-sdk-python/blob/main/src%2Fanthropic%2Ftypes%2Fmessage_create_params.py#L146

Valid are "string" and [{type:"text", text:"..."}, ..] for now. But you can see where this is going.

**Comment by enricoros** [comment]
@hourianto you got it. LMK if this works as expected.
![image](https://github.com/user-attachments/assets/9487d8d6-2c7a-4bb4-b6ce-b6e8c852cbb8)

**Comment by enricoros** [comment]
@hourianto today Anthropic released a new API, and in the first example they show a system prompt with 2 parts :)

https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#can-i-use-prompt-caching-at-the-same-time-as-other-betas

Please let em know if you still need this feature, because I may revert it, for the purpose of adding support for caching.

**Comment by hourianto** [comment]
@enricoros yeah, I saw it too, I guess I'll just patch it on the proxy :)
