### ISSUE TITLE
[BUG] Unable to Input Image to Any Model

### ISSUE THREAD

**Issue by sam0jones0** [enricoros/big-AGI#630]
### Description

visit https://get.big-agi.com/

Try to input image as per screenshot

Get error message file type is not compatible with model. Tested with all Anthropic / OpenAI models.

### Device and browser

Tested on Firefox 129.0.2 (64-bit) and Chrome Version 128.0.6613.113 (Official Build) (64-bit)

### Screenshots and more

![bigagibug](https://github.com/user-attachments/assets/2319c1b9-d84d-4af0-ba98-bd03d3ba6009)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Yes, this is supported by Big-AGI 2 (the upcoming release) while big-AGI 1 only supported text and is the stable release currently deployed on get.big-agi.com. This will be fixed when 2 is released on our site.
