### ISSUE TITLE
[BUG] Custom Personas Not Persisting After Reload

### ISSUE THREAD

**Issue by mabduqayum** [enricoros/big-AGI#633]
### Description

The website currently does not retain user-created custom personas between sessions. When a user creates a custom persona and reloads the browser, the persona is lost.

### Expected Behavior
- Custom personas created by users should be saved and remembered.
- Users should be able to see and select their previously created custom personas.
- The system should allow users to manage (edit, delete) their saved custom personas.

### Current Behavior
- Custom personas are only available for the duration of the current session.

### Steps to Reproduce
- Navigate to the persona creation section.
- Create a new custom persona with specific attributes.
- Use the custom persona in a conversation or task.
- Reload the browser.
- Attempt to find or use the previously created custom persona.

- This issue affects user experience and productivity, as users cannot build a library of personalized personas over time.

### Device and browser

- Browser: Chrome 128
- Operating System: Windows 11

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by mabduqayum** [comment]
Duplicate of #340

**Comment by DoS007** [comment]
This is more precise and less comprehensive/extensive than the referenced issue.

**Comment by DoS007** [comment]
@mabduqayum Your issue and your description is valid (and good), but please delete or change the screenshots as they are a bit missleading. This is big-agi not chatbox.

**Comment by enricoros** [comment]
Thanks @mabduqayum for reporting and @DoS007 for looking into this and advising for the change.

This will be done as part as #35, in a full redo of the Personas system. So I'll be closing this for now as it's included in what will be coming soon in big-AGI 2.

**Comment by DoS007** [comment]
@enricoros Will the reset/ not storing of the custom prompt also be fixed :)?

![grafik](https://github.com/user-attachments/assets/624bcacf-1abb-4e64-8274-c9cb4fb5048a)
