### ISSUE TITLE
[BUG] Gemini 1.5 Pro 002 and Flash 002 Models - Service Parsing Issue

### ISSUE THREAD

**Issue by darthalex2014** [enricoros/big-AGI#648]
### Description

When using the new Gemini 1.5 Pro 002 and Flash 002 models, a service parsing issue occurs, resulting in an error message. This issue seems to be related to the "index" field within the "candidates" array in the response data, which is expected to be a number but is received as undefined.

Expected Behavior:
The response should not contain any error messages and the "index" field within the "candidates" array should be populated with a number.

Actual Behavior:
The response contains an error message indicating a service parsing issue related to the missing "index" field.

Affected Models:
Gemini 1.5 Pro 002
Gemini 1.5 Flash 002

Aix.Gemini (dispatch-parse):  **[Service Parsing Issue] Gemini**: [
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "undefined",
    "path": [
      "candidates",
      0,
      "index"
    ],
    "message": "Required"
  }
].
Input data: {"candidates": [{"content": {"parts": [{"text": "The"}],"role": "model"}}],"usageMetadata": {"promptTokenCount": 29239,"totalTokenCount": 29239}}.
Please open a support ticket.
 POST /api/trpc-edge/aix.chatGenerateContent?batch=1 200 in 2452ms

### Device and browser

Chrome Lastest, Windows, Latest big-AGI and big-agi-2-6d47b60

### Screenshots and more

![image](https://github.com/user-attachments/assets/f0bdcba5-1c75-4328-93e1-d41982b40435)
![image](https://github.com/user-attachments/assets/b63cf340-3817-4558-bac3-e22a2f04163c)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@darthalex2014 please try now.

**Comment by darthalex2014** [comment]
> @darthalex2014 please try now.

[3158d5b](https://github.com/enricoros/big-AGI/commit/3158d5b340853a47d1d95c19d5a6cbaf2a473177) work
![image](https://github.com/user-attachments/assets/ecf3388b-7933-401f-bb9d-1be9f35d0a3a)
