### ISSUE TITLE
High token usage via OpenRouter

### ISSUE THREAD

**Issue by jakemkc** [enricoros/big-AGI#650]
### Description

Dear all,

I have been using big-AGI for a while and I love it.  I didn't install it but use the provided web interface with my open OpenRouter api key (gpt-4o)

I observed high usage cost in OpenRouter and try to figure out what's the problem.

I figured out that for the same simple question, my prompt's token usage via big-AGI is 10 times more than other similar services.

For example:
I type "Hi" in the general default mode in big-AGI as my input prompt, the token is "20,402" in OpenRouter record
I type "Hi" in chatbox (web.chatboxai.app) as my input prompt, the token is "1,996"

for "how are you?" in big-AGI: input token is "20,423"
for "how are you?" in chatbox: input token is "2,008"

I wonder if I have done something wrong in the settings?

Best,
Jake

### Device and browser

macos 12.7.1
firefox browser 130.0.1 (64-bit)

### Screenshots and more

<img width="1139" alt="Shot 15" src="https://github.com/user-attachments/assets/eaa93c6b-bd84-4454-840c-5fa2a9219c00">
<img width="916" alt="Shot 16" src="https://github.com/user-attachments/assets/1ff94aba-c6af-4ebf-88ef-0cf938712420">
<img width="942" alt="Shot 17" src="https://github.com/user-attachments/assets/4bcf6234-0b92-4f2b-80be-4c4078924a46">

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by FarVision2** [comment]
(from the i in Tokens Column)
The number before the arrow is the number of tokens in the prompt (or all messages you sent, including previous history).
The number after the arrow is the number of tokens in the completion.
Different models tokenize text in different ways. They usually represent between 2 to 4 characters.

If you select the session under Provider in OpenRouter  you will get the particulars as well as the generation ID which you can review for the exact API call

**Comment by jakemkc** [comment]
> (from the i in Tokens Column) The number before the arrow is the number of tokens in the prompt (or all messages you sent, including previous history). The number after the arrow is the number of tokens in the completion. Different models tokenize text in different ways. They usually represent between 2 to 4 characters.
> 
> If you select the session under Provider in OpenRouter you will get the particulars as well as the generation ID which you can review for the exact API call

Thank you for the explanation. After clearing the history everything is back to normal.

Jake

**Comment by jakemkc** [comment]
> (from the i in Tokens Column) The number before the arrow is the number of tokens in the prompt (or all messages you sent, including previous history). The number after the arrow is the number of tokens in the completion. Different models tokenize text in different ways. They usually represent between 2 to 4 characters.
> 
> If you select the session under Provider in OpenRouter you will get the particulars as well as the generation ID which you can review for the exact API call

Thank you for the explanation. After clearing the history everything is back to normal.

Jake
