### ISSUE TITLE
[BUG] https://big-agi.com/docs/deploy-docker link is dead

### ISSUE THREAD

**Issue by TimeScience** [enricoros/big-AGI#655]
### Description

[https://big-agi.com/docs/deploy-docker](https://big-agi.com/docs/deploy-docker) throws a 404

### Device and browser

win11 chrome

### Screenshots and more

![image](https://github.com/user-attachments/assets/56d27539-961b-4850-87b0-5c7e043a75fe)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks for finding this @TimeScience. Deployment guides are now published on the website, including:
https://big-agi.com/docs/deploy-docker
