### ISSUE TITLE
[Roadmap] Copy specific message as markdown

### ISSUE THREAD

**Issue by tsoernes** [enricoros/big-AGI#656]
**Why**
Very useful to be able to copy a specific message in markdown format

**Description**
Copy selected text or entire message with markdown formatting

**Comment by enricoros** [comment]
You can click on this Copy button, no? It would take the entire message.
![image](https://github.com/user-attachments/assets/be27cf04-ef45-4327-8856-a49509cf54f3)

**Comment by tsoernes** [comment]
Yes that already works.
