### ISSUE TITLE
[Roadmap]

### ISSUE THREAD

**Issue by Prof-pengyin** [enricoros/big-AGI#664]
**Why**
(replace this text with yours) The reason behind the request - we love it to be framed for "users will be able to do x" rather than quick-aging hype-tech-of-the-day requests

**Description**
Clear and concise description of what you want to happen.

**Requirements**
If you can, Please break-down the changes use cases, UX, technology, architecture, etc.
- [ ] ...

**Comment by enricoros** [comment]
Empty.
