### ISSUE TITLE
[BUG] PDF Worker is not working in latest big-agi-2

### ISSUE THREAD

**Issue by engineeringvintana** [enricoros/big-AGI#666]
### Description

The API version is not compatible with the worker version when trying to upload a file in the prompt box.

### Device and browser

MacBook Pro - Google Chrome v129

### Screenshots and more

![Screenshot 2024-10-24 at 12 37 46 PM](https://github.com/user-attachments/assets/de854b82-b9aa-4919-8a91-09c747d84bf1)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks @engineeringvintana, you need to update the NPM packages in your installation. `npm i` on the terminal, and then re-build it. Will do.

**Comment by enricoros** [comment]
Thanks @engineeringvintana, you need to update the NPM packages in your installation. `npm i` on the terminal (the message says that what you built with 4.6 does not match the latest in the code 4.7), and then re-build it. Will do.
