### ISSUE TITLE
[BUG] Add new Anthropic Claude Sonnet 3.5 20241022

### ISSUE THREAD

**Issue by mabduqayum** [enricoros/big-AGI#667]
### Description

Add sonnect 3.5 20241022 version.
Currently there is use latest sonnect 3.5 version as shown in screenshot.

### Device and browser

All devices

### Screenshots and more

![image](https://github.com/user-attachments/assets/5bc0184d-66ec-48c4-b881-1a83b74360f2)
![image](https://github.com/user-attachments/assets/f4b3b2ae-36e1-458f-bb39-dcce41cf7695)

Can't use latest sonnet 3.5 version here
![image](https://github.com/user-attachments/assets/485de167-c88e-44eb-8e9f-09deb39364d6)
![image](https://github.com/user-attachments/assets/67a31f6d-9d8f-472c-92fc-0be928b40687)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@mabduqayum Fixed and web app updated. https://github.com/enricoros/big-AGI/commit/d712c275a0d3531f3d50bcd0ed090ade6b7a627c
