### ISSUE TITLE
[BUG] openrouter. sometimes or always? big agi doesnt show what error the llm/provider delivered. perhaps related to current cloudflare 524 error

### ISSUE THREAD

**Issue by stjema** [enricoros/big-AGI#673]
### Description

![image](https://github.com/user-attachments/assets/b18a9a7a-2593-4cd5-a9ba-97d185cc8029)
it just looks like this and it doesnt show up as an finished prompt on openrouter. 
browser being used for big agi. chrome.

### Device and browser

chrome

Request timeout investigation (524 errors) from cloudflare currently going on

**Comment by enricoros** [comment]
I cannot reproduce with any version of big-agi. @stjema is it cloudflare?

**Comment by stjema** [comment]
i think the issue is gone so it was cloudflare.
are u not in the openrouter discord server for news? then u can tell big agi users what is going on.

**Comment by enricoros** [comment]
@stjema no, I'm on a discord diet right now, just cut all comms channels to ship Big AGI 2.0 soon.

**Comment by stjema** [comment]
is v2 so much better? :P

**Comment by enricoros** [comment]
@stjema MUCH, in every way.

**Comment by enricoros** [comment]
Closing - note that in the v2 branch I've updated by much the Openrouter provider today, with models sorted better.
