### ISSUE TITLE
[BUG] [Stream Issue] Gemini 1.5 pro latest - tested with 2 API KEYS

### ISSUE THREAD

**Issue by johnfelipe** [enricoros/big-AGI#675]
### Description

[Stream Issue] Gemini: [ { "code": "invalid_type", "expected": "number", "received": "undefined", "path": [ "candidates", 0, "index" ], "message": "Required" } ]

![SNAG-0177](https://github.com/user-attachments/assets/7775d2ea-14e6-4a74-8ce1-54fe0d2182b9)

### Device and browser

windows 10
chrome latest version

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@johnfelipe which branch is this on? 

It's working for me on the `v2-dev` branch as of now.
![image](https://github.com/user-attachments/assets/da9c78c2-41e2-4aeb-96ee-37b612bd7206)

**Comment by enricoros** [comment]
Thanks @johnfelipe I found the issue (not present in Big-AGI 2, but was still present in 1) - fixed, sorry for the downtime (Google changed the protocol). I'm confident you'll love the Gemini support in Big-AGI 2.

**Comment by johnfelipe** [comment]
Can you share me steps for update to V2 in ver El
I fork you repo and when sync all is automatic 
How can upgrade to V2 pls

**Comment by johnfelipe** [comment]
Para cambiar la rama (branch) de un fork y sincronizarlo con la rama v2-dev del repositorio original, puedes seguir estos pasos:

1. Desde tu fork local (en tu computadora):
```bash
# Añadir el repositorio original como remote si aún no lo has hecho
git remote add upstream https://github.com/enricoros/big-AGI.git

# Obtener todas las ramas del repositorio original
git fetch upstream

# Cambiar a una nueva rama v2-dev local
git checkout -b v2-dev

# Sincronizar tu rama v2-dev con la del repositorio original
git reset --hard upstream/v2-dev

# Subir los cambios a tu fork en GitHub
git push -f origin v2-dev
```

2. Desde la interfaz web de GitHub:
- Ve a tu fork en GitHub
- Haz clic en el menú desplegable de ramas (donde dice "main" o "master")
- Selecciona o crea la rama "v2-dev"
- Ve a "Settings" de tu repositorio
- En la sección "General", desplázate hasta "Default branch"
- Cambia la rama predeterminada a "v2-dev"
- Confirma el cambio

3. Para mantener el fork sincronizado en el futuro:
```bash
git fetch upstream
git checkout v2-dev
git merge upstream/v2-dev
git push origin v2-dev
```

Si estás usando Vercel:
1. Ve al dashboard de tu proyecto en Vercel
2. Ve a "Settings" → "Git"
3. En "Production Branch", cambia la rama a "v2-dev"
4. Redespliega el proyecto para que use la nueva rama

Ten en cuenta que la rama v2-dev es la rama de desarrollo para Big-AGI 2, que según el README se lanzará en Q4 2024 y puede contener cambios experimentales o inestables.

**Comment by enricoros** [comment]
^ si
