### ISSUE TITLE
[Idea] Search functionality based on the content of chats

### ISSUE THREAD

**Issue by darthalex2014** [enricoros/big-AGI#676]
![image](https://github.com/user-attachments/assets/53048125-f068-4758-a049-82ed9e3ef6c2)
![image](https://github.com/user-attachments/assets/fde6553d-bb59-4033-b1bc-6af6f0a42a6d)
Would it be possible to implement search functionality based on the content of chats?

I have nearly 500 chats... And because I'm lazy and don't delete old ones/don't sort them among the clutter, I can't find the chats I need :D

If it were possible to search by content, it would be really awesome.

**Comment by darthalex2014** [comment]
Wow... im Slowpoke

**Comment by enricoros** [comment]
Thanks @darthalex2014 ! I hope that I'll be able to give you soon tools to auto-archive older chats, while keeping the ones that are more important. Wow, you're a PRO!
