### ISSUE TITLE
[BUG] Azure GPT 4o is limited to maximum 4096 output tokens even though model supports 16,384

### ISSUE THREAD

**Issue by tsoernes** [enricoros/big-AGI#677]
### Description

Cannot set it higher than 4096 even though model supports it. 

### Device and browser

Linux

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Closing as support was provided and Azure doesn't provide the context windows.
