### ISSUE TITLE
[BUG] Ollama AIX Configuration Issue

### ISSUE THREAD

**Issue by matrix303** [enricoros/big-AGI#678]
### Description

Setup Ollama + bigAGI fresh install. I have followed the basic steps. Ollama has been verified to work with other apps. I added Ollama to the bigAGI as a service provider and can see the models. I am on v2-dev

When in chat mode, I try to start a chat it gives me this error in the chat UI:
```
[AIX Configuration Issue] Ollama: Ollama is not supported in this context
```

and this error in the server:
```
Aix.Ollama (dispatch-prepare): **[AIX Configuration Issue] Ollama**: Ollama is not supported in this context
```

Ollama service notes the requets but shows no error. 

Would appreciate any help

### Device and browser

Linux Local deployment with npm

### Screenshots and more

<img width="841" alt="image" src="https://github.com/user-attachments/assets/5dcd6767-5b01-41fa-a5c8-1a9a9f78eb8e">
<img width="681" alt="image" src="https://github.com/user-attachments/assets/6e19227f-c97a-4040-a218-89620e04c614">

### Willingness to Contribute

- [X] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
True, Ollama has not been ported to AIX (big agi 2 new AI engine) yet.

Model listing is working, but ollama has some non standard protocol that needs to be implemented.

AIX has new native support for OpenAI-compatible, Anthropic, and Google protocols, but not Ollama yet.

It's likely not much work to do it, so if anyone wants to contribute it, I'd welcome a PR. I'm working on the official 2.0 release which will likely come without Ollama support at launch unless someone steps in and puts the day of work that's required to make and this.

**Comment by enricoros** [comment]
@matrix303 try now ;) simple fix, seems to work very well, including images (PNG only) with Vision. 
![image](https://github.com/user-attachments/assets/eef2ecac-aacb-4bcf-9566-ca7e3ad5ad3b)

**Comment by enricoros** [comment]
@matrix303 correct - that was the first out of 4 commits to fix ollama; it only updated the models. It was actually the next commit that brought in the bulk of the fixes. 

Go with the current head of v2-dev, or 1811e31ea5c8a79bf5cc3641289b57655154cbf5 to be safe.

**Comment by matrix303** [comment]
@enricoros, got it working! for some reason I had to reclone the git repo but its very likely due to my own "explorations" into trying to get it working.

Cheers

**Comment by enricoros** [comment]
Great, let me know how it is, the integration should be solid @matrix303
