### ISSUE TITLE
[Roadmap] Azure Serverless API models

### ISSUE THREAD

**Issue by mohitkr123** [enricoros/big-AGI#679]
**Why**
Currently we can only use Azure with openai models only. However, Azure has vast selection of models. They can be deployed only as serverless API. 

**Description**
So would it be possible to integrate the functionality of this? 

**Requirements**

**Comment by enricoros** [comment]
@mohitkr123 do you have example of the endpoint name for a model, and what's the API interface? (Whether it's open AI compatible or not, otherwise our backend doesn't know how to talk to them). Please link to any docs that explains this.

**Comment by enricoros** [comment]
Closing for missing follow up.
