### ISSUE TITLE
[BUG] OpenAI's o1-preview and o1-mini models not working

### ISSUE THREAD

**Issue by jelmerkk** [enricoros/big-AGI#682]
### Description

Whenever I try to use the o1-preview or the o1-mini model, I get this reponse:
```
[Service Issue] Openai: Bad Request (400): "error": { "message": "Unsupported value: 'messages[0].role' does not support 'system' with this model.", "type": "invalid_request_error", "param": "messages[0].role", "code": "unsupported_value" }
```

### Device and browser

Macbook Pro M1 on Arc/Chrome/Safari

### Willingness to Contribute

- [x] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by genchadt** [comment]
Dropping in to state that I'm having the same issue. I've deleted and re-added the API token to get access to o1 models but receive this same error message.

**Comment by enricoros** [comment]
@genchadt @jelmerkk Version 2 of Big-AGI dropping soon with full support for o1.
In the meantime you can:
1. build the `v2-dev` branch yourself until the official app is out in the next few weeks
2. use o1 via the `openrouter` provider (openrouter is a great model server that makes new models available sooner)
3. use the model on chatgpt until V2 is out.

**Comment by genchadt** [comment]
> @genchadt @jelmerkk Version 2 of Big-AGI dropping soon with full support for o1. In the meantime you can:
> 
> 1. build the `v2-dev` branch yourself until the official app is out in the next few weeks
> 2. use o1 via the `openrouter` provider (openrouter is a great model server that makes new models available sooner)
> 3. use the model on chatgpt until V2 is out.

Thanks for the response. I have switched to v2-dev and it is working, however I did need to re-generate my API key.

**Comment by genchadt** [comment]
> > Thanks for the response. I have switched to v2-dev and it is working, however I did need to re-generate my API key.
> 
> How did you manage to build it locally, the latest v2-dev? On my device, I've got a build error: `Error: Failed to collect page data for /draw`.
> 
> Any tips?

Here's what I did (I am a git noob)

1. Deleted the big-agi root folder
2. Cloned v2-dev from scratch
3. Run `npm install` then `npm run build`

**Comment by enricoros** [comment]
Great job @genchadt and @balintbabics . I'm close to publish the first V2 officially on Big-AGI.com and very excited about cloud backups and all. Working very very hard on it, and there's so much I want to ship once this major milestone of having the big-agi cloud is done.

**Comment by darinkishore** [comment]
> Great job @genchadt and @balintbabics . I'm close to publish the first V2 officially on Big-AGI.com and very excited about cloud backups and all. Working very very hard on it, and there's so much I want to ship once this major milestone of having the big-agi cloud is done.

Hey, you're doing really great work. Thank you so much for creating this. I love using it. I use it almost every day. It's incredible that Big-AGI is fucking open source and works, and the thought put in on UX is amazing.

**Comment by 0xhankoc** [comment]
Any updates om this @enricoros ? 

I'm still getting the same error as 

> ### Description
> Whenever I try to use the o1-preview or the o1-mini model, I get this reponse:
> 
> ```
> [Service Issue] Openai: Bad Request (400): "error": { "message": "Unsupported value: 'messages[0].role' does not support 'system' with this model.", "type": "invalid_request_error", "param": "messages[0].role", "code": "unsupported_value" }

I was planning to set up Big-AGI as an internal tool for our dev team but not being able to use o1-preview and o1-mini are blocking. We purchased OpenAI credits in bulk so it's not feasible for us to switch to openrouter now. 

Do you have an ETA on using o1-preview / o1-mini with big-agi-v2 without an aggregator ?

**Comment by enricoros** [comment]
Can you confirm you're on the `v2-dev` branch? It's been working well, I just pushed some commits yesterday as well to enable streaming mode with o1.

**Comment by genchadt** [comment]
> Any updates om this @enricoros ?
> 
> I'm still getting the same error as
> 
> > ### Description
> > Whenever I try to use the o1-preview or the o1-mini model, I get this reponse:
> > ```
> > [Service Issue] Openai: Bad Request (400): "error": { "message": "Unsupported value: 'messages[0].role' does not support 'system' with this model.", "type": "invalid_request_error", "param": "messages[0].role", "code": "unsupported_value" }
> > ```
> 
> I was planning to set up Big-AGI as an internal tool for our dev team but not being able to use o1-preview and o1-mini are blocking. We purchased OpenAI credits in bulk so it's not feasible for us to switch to openrouter now.
> 
> Do you have an ETA on using o1-preview / o1-mini with big-agi-v2 without an aggregator ? Happy to lend a hand if you can link issues regarding this.

Here's what I did (I am a git noob)

1. Deleted the big-agi root folder
2. Cloned v2-dev from scratch with git clone -b v2-dev https://github.com/enricoros/big-AGI.git
3. Run `npm install` then `npm run build`
4. Opened big-agi and re-added my API key (think I could've just used the models refresh button there tho)

**Comment by 0xhankoc** [comment]
@enricoros did a clean install & build on `v2-dev`, everything works fine. Tried to reproduce the problem but failed to do so. Thanks!

**Comment by wac81** [comment]
i build on v2-dev but i got error:

Transformation error: AIX: Error in response: ❌ **[Openai Issue]:** Invalid prompt: your prompt was flagged as potentially violating our usage policy. Please try again with a different prompt: https://platform.openai.com/docs/guides/reasoning/advice-on-prompting

**Comment by enricoros** [comment]
@wac81 that's OpenAI's content filter. They didn't like the input (o models are exceptionally strict and with plenty of moderation false positives). I.e. nothing we can do about it.

**Comment by wac81** [comment]
Thank you for your answer
