### ISSUE TITLE
recurrent "fetch failed" issues across multiple vendors/api keys [BUG]

### ISSUE THREAD

**Issue by TimeScience** [enricoros/big-AGI#684]
### Description

I'm having a new issue where every time I submit a new message, I get the error below. If I right click and "Restart from here", it goes through fine. This was not happening until a few weeks ago and it happens for both OpenAI and OpenRouter (with all models) so it doesn't seem vendor specific.

_[Service Issue] Openai: fetch failed · {"errno":-3001,"code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"api.openai.com"}_

Searching through previous posts, it seems like this might be a timeout issue, but it would be some sort of "keep-alive" thing because if I send a new message right after one that worked, it goes fine, but then if I wait a while (like more than a few minutes), it seems to timeout again and the next message will need to be re-sent before it works.

### Device and browser

Windows 11; Chrome

Pre-built docker (happening on both of the most recent dockers):
ghcr.io/enricoros/big-agi:sha-32861ea
ghcr.io/enricoros/big-agi:sha-b20d65e

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Unrelated to Big-AGI -- some issue with docker containers. Other projects that use different AI stacks display the same issue: https://github.com/lobehub/lobe-chat/discussions/3828 

Hence closing.
