### ISSUE TITLE
[BUG] Repeated / duplicate experimental Gemini models

### ISSUE THREAD

**Issue by dandv** [enricoros/big-AGI#690]
### Description

After entering my Google AI Studio API key, I see what appears to be duplicate Gemini Experimental models (3 `1206` ones, and 2 `1121` ones). After mousing over them, identical models display identical tooltips.

### Device and browser

Chromium 125.0 on Fedora Linux

### Screenshots and more

![image](https://github.com/user-attachments/assets/8b4d62c5-60ab-4919-b33c-86c4cf4d584c)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
I've requested for info in the Gemini API discord - no official answer.
Likely cause: Gemini replaced old models (including Flash models(!)) with Gemini Experimental 1206. See https://discord.com/channels/1009525727504384150/1182420115661267085/1315090423383068743 for details.

Workaround: for the time being, I'm forcefully removing the models that Gemini replaced with 1206 with no explanation. Note: this will require us to go back and fix every time Gemini decides to replace a model -- definitely not a scalable solution.

**Comment by enricoros** [comment]
Resolved by having a list of models that are not what they say they are - and hance we remove them to avoid confusing our users.
