### ISSUE TITLE
[BUG] Broken image "big-AGI BEAM Rays" on beam welcome page

### ISSUE THREAD

**Issue by dandv** [enricoros/big-AGI#691]
### Description

When landing on the Beam welcome page, the image doesn't load. I've disabled any extensions that might interfere.

### Device and browser

Chromium 125 on Linux

### Screenshots and more

![image](https://github.com/user-attachments/assets/a8906ddf-2208-46ca-81d6-01db4e46464d)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
@dandv - thanks for reporting. Fixed.
