### ISSUE TITLE
big-AGI version 2.0 

### ISSUE THREAD

**Issue by ppnine1234** [enricoros/big-AGI#697]

**Comment by enricoros** [comment]
@ppnine1234 hi, what's this request about?

**Comment by PrivTEC** [comment]
### A Note on Impatience in the Porcelain Shop 🏺

Dear **ppnine1234**,  
Your enthusiasm for **big-AGI 2.0** is almost tangible – a beautiful testament to the fact that this project not only exists but truly inspires. Your impatience is less of a critique and more of a great compliment to the developer. It shows how much you’re anticipating the release, much like a child eagerly awaiting Christmas morning – a compliment that speaks volumes. 🎄✨  

**Enrico**,  
Your dry humor and elegant avoidance of making concrete promises are remarkable. A sort of *“Zen master of the GitHub universe”*, teaching us all that _“the journey is the destination.”_ It takes creators like you – this minimal, almost vanishingly small fraction of humanity – to truly build and lay the foundation for innovation. Without you, the world would be a stagnant place. 🌍🔥  

### To Both of You  
Perhaps it is this very dynamic – the impatience of users and the patience of developers – that drives projects like **big-AGI** forward. Let’s acknowledge with a wink 😉 that we are all drawing from the same source: the desire to create something great. And let’s not forget that it is only through the rare spark of creativity, burning within creators like you, **Enrico**, that such projects become possible at all. 🙌

---
✨ _Big ideas take time. Big releases, even more._ ✨

**Comment by enricoros** [comment]
@PrivTEC it's hard to decode the GPT sarcasm for me - despite using lots of GPT in every day's work, I'd appreciate no not waste time reading AI slop. I could be wrong so someone else please decode.

This is a long standing high-quality project that thousands of people use successfully whether on the website or built from their branch. You are welcome to stick around for the 2.0 release, which will include a cloud component, images support and dynamic personas.

**Comment by PrivTEC** [comment]
@enricoros Anscheinend arbeitest du so oft mit KIs, dass du bereits überall Gespenster siehst, was dazu führt, dass du mich ohne Grund abrupt angreifst. Vielen Dank.

Abgesehen davon hoffe ich doch sehr, dass du begreifst, dass es Menschen gibt, deren Muttersprache nicht Englisch ist. Schon mal darüber nachgedacht, dass es sich hier um eine Übersetzung handeln könnte, oder bist du bereits so verblendet, dass du von nichts anderem mehr ausgehen kannst?

Mein Posting war als Unterstützung gemeint.
Mir direkt etwas zu unterstellen, ist eine absolute Frechheit. Ich denke, der Unsinn hier kann geschlossen werden.

**Comment by enricoros** [comment]
There are evidently issues in translation on both sides, hence I'm marking this as off-topic.
