### ISSUE TITLE
[Roadmap] Can Big-AGI generate images on OpenAI API

### ISSUE THREAD

**Issue by Llaves** [enricoros/big-AGI#704]
The readme contains a image of a chat with GPT-4 Turbo that prompts for an image and the image is shown. I tried this myself and get back a message that it can't produce images. Can images be produced, and if so, how. I know the generations endpoint of the API will create images, but apparently this is not being called. Do I have to change an option in the model settings?

**Comment by enricoros** [comment]
Thanks for the report @Llaves . Can you type "/draw a circle" (without quotes) and attach the screenshot containing the error message?

**Comment by Llaves** [comment]
operator error - didn't realize I had to use "/draw"in the prompt.

**Comment by enricoros** [comment]
@Llaves I'll make this more intuitive in a future release, and also enable the "draw tool" so that the model will initiate the drawing without typing /draw. closing this for now, but it will come.
