### ISSUE TITLE
[Roadmap] Take advantage of OpenAI Realtime API, Google's Multimodal Live API, etc.

### ISSUE THREAD

**Issue by atxcowboy** [enricoros/big-AGI#708]
**Why**
Enhancing big-AGI's call functionality to include video calls and screen sharing can significantly improve user engagement and collaboration. Leveraging APIs like OpenAI's Realtime API or Google's Multimodal Live API enables seamless integration of these features. To manage increased costs, it's advisable to offer this enhanced experience as an optional feature, allowing users to choose between the existing and new functionalities.

**Description**
Upgrade big-AGI's communication capabilities by integrating video calling and screen sharing features. This enhancement will utilize advanced APIs to provide real-time, multimodal interactions, thereby enriching user experience significantly.

**Requirements**
Use Cases:
- Users can engage in real-time video calls with then A where users allow either access to the camera or constant screen sharing.
- The screen sharing would facilitate the sharing of documents, presentations, or applications during calls.
- Users need to opt for video and screen sharing capabilities as needed, ensuring flexibility and cost management.

User Experience:
- Keep it intuitive and implement user-friendly controls for initiating video calls and screen sharing.
- Ensure smooth switching between audio-only and video calls without disrupting the ongoing conversation.
- This effort would provide very low-latency communication.

Technology:
- You would need to implement WebRTC protocols to facilitate one way peer-to-peer video and two way audio communication.

**Comment by enricoros** [comment]
Please, please, please, do not use AI to write tickets. AI adds words (leveraging, seamless, etc.) and embellishments that REMOVE meaning and hide the real request under.

Sounds counterintuitive for an AI app, but I want people to use AI to "compress" their requests, not to make them larger. 

The result is that the text looks longer and a waste of time to read.

**Comment by enricoros** [comment]
Closing because it's too vague for implementation - will open more precise tasks about this when we understand how the UI/UX for that integration would look like.
