### ISSUE TITLE
Icons - VOTE!

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-agi#77]
Do you like any of the following icons as the main icon of the app? (selected between 200 icons generated by stable diffusion).

Want to have the idea of 'structure', 'calligraphy', 'editing', 'thought', 'knowledge'.

**Icon A)**
![icon1](https://user-images.githubusercontent.com/32999/231358922-cbbb9bc6-5682-4244-9515-cd48e6b373c3.png)

**Icon B)**
![2884033731_curly brace, brace logo, minimal, calligraphy, bla_xl-beta-v2-2-2](https://user-images.githubusercontent.com/32999/231358971-00491c99-ec8c-48ff-b0e3-165373088541.png)

Let me know, @fredliubojin , @jondwillis , @harlanlewis , @typpo , @seven4x , @koganei , @nilshulth , @peperunas, @rossman22590.

**Comment by seven4x** [comment]
personally vote B

**Comment by jondwillis** [comment]
I vote A, but just barely. Whatever the choice, it may be worth running through a human artist or another algorithm that can make it more accessible/distinguished as an icon (remember icons are often very small, so detail can get in the way)
