### ISSUE TITLE
Chat as a process

### ISSUE THREAD

**Issue by enricoros** [enricoros/big-agi#79]
Consider chat itself as an AGI operation.
This improvement would abstract the chatting function itself, to enable different interactions (UX), agi products (Product), easier development (DX), and composability. 

Abstracted Components: Context, Timeline, Operators (incl. Pre/Post processors).
 - the process for an assistant response may include: gathering inputs, injecting context, recursive context pre-processing, generation, post-processing, all while rendering w/optional devtolling
 - example new functionality: squash: f(Purpose, Log, Context) -> (Log1, Context1). "Compression of a chat up to this point (discarding potentially irrelevant information) into a single message in the Log, and potentially smaller context"
 - other example: #78, referral to a new chat (with different purpose)

There would be endless new useful functionality once the technology is refactored from this over-fit chat paradigm (and implementation).

High stress on reusability, zero-lag impact on the base case, auto-progressive rendering, and composability.

Me and gpt4 can take care of the refactoring. @fredliubojin, #78 - heavy inspired.

**Comment by jondwillis** [comment]
https://github.com/hwchase17/langchainjs -- I just found out that this exists. Highly relevant to anything "AGI"

**Comment by enricoros** [comment]
Interesting. Thanks for the share. I believe we can do something better also :)
