### ISSUE TITLE
Feature request: "Top P" in Advanced AI settings

### ISSUE THREAD

**Issue by epylar** [enricoros/big-AGI#84]
I like to set my "Top P" to 0.5 alongside my temperature of 0.5 for programming questions with GPT-4. Could this be added to Advanced AI settings?

**Comment by enricoros** [comment]
For sure, easy to do. Just out of curiosity: what does it do to the generation? (Asking for subjective experience) and would it be worth to do it by default on the Developer profile?

**Comment by epylar** [comment]
> For sure, easy to do. Just out of curiosity: what does it do to the generation? (Asking for subjective experience) and would it be worth to do it by default on the Developer profile?

It makes it less creative and more accurate. For each generation, GPT has a list of tokens and probabilities. At 1.0 it can choose any of them. At 0.5 it can only choose the top half. However, open AI recommends that you only set either temperature or top P but not both. To be honest, I don't have a great feel for how they change the results yet. I'm still fiddling with the parameters. It would be nice to have a formal benchmark of how they affect accuracy in programming.

**Comment by epylar** [comment]
(I think this means that Open AI is suggesting that if one of them is reduced, leave the other one at 1.0)

**Comment by enricoros** [comment]
I achieve the same with the "temperature" - when I want it to be more creative/explorative (and maybe have errors :) I set a temperature closer to 1. With a temperature of 0, it will always be the most obvious and fitting code.

I wonder how to convey in the UI to change top_p OR temperature. It's very deep down in the details for people.

**Comment by epylar** [comment]
@enricoros That's tricky.. maybe a selector between Top P and Temperature, and a slider to set the one selected. Feels a little awkward though.

**Comment by enricoros** [comment]
It's actually a great idea.
