### ISSUE TITLE
multiple PDF ingestion with namespace with pinecone

### ISSUE THREAD

**Issue by DjangoMaker** [enricoros/big-AGI#88]
Is it possible to do the following?
let the LLM ingest multiple PDF into embeddings, each PDF creating a namespace with realated vectors stored in Pinecone?

On the UI side, one can create a "custom" setting for each document category, example: Car engines. User can specify PDF document(s), chunk size, chunk_overlap

Then that ingested data can be interrogated?

**Comment by enricoros** [comment]
This is very interesting. From a high level, I see using embeddings as a DIY attention mechanism. We have support for reduction of PDFs that do not fit into the context window, but what you're asking is different.

Help us pave the way with s couple of questions:

 - generation of the embeddings: if I read you correctly, one would specify the file, chunk size, chunk overlap, and a namespace named after the PDF would be created, with embeddings (e.g. ada-002) representing each chunk. is this correct? Are there smart ways of 'chunking'?

 - usage of the embeddings: how and when do we query/retrieve the embeddings (from pinecone or whatever) and use them?

Please let me know @DjangoMaker , this is interesting.

**Comment by DjangoMaker** [comment]
This is a chart I found [https://github.com/mayooear/gpt4-pdf-chatbot-langchain/blob/main/visual-guide/gpt-langchain-pdf.png](url) hope it helps.

**Comment by DjangoMaker** [comment]
here is the code that accomplishes the task just CLI, need to integrate with the UI here.
https://github.com/angad/dharamshala/blob/main/docs.py

**Comment by enricoros** [comment]
Superseded by RAG techniques, will be delivered independently from Pinecone.
Closing for duplication / n/a.
