### ISSUE TITLE
Occured the `ConnectTimeoutError` when I ran the project locally

### ISSUE THREAD

**Issue by fox20431** [enricoros/big-agi#95]
Hi, I occurred the `ConnectTimeoutError` when I ran the project locally.

The command that I used:

```sh
git clone git@github.com:enricoros/big-agi.git
cd big-agi
npm install
npm run dev
```

---

This is my `.env` content; I just added the parameters of OpenAI.

```
# [Recommended for local deployments] Backend API key for OpenAI, so that users don't need one (UI > this > '')
OPENAI_API_KEY=MY_OPENAI_API_KEY
# [Not needed] Set the backend host for the OpenAI API, to enable platforms such as Helicone (UI > this > api.openai.com)
OPENAI_API_HOST=api.openai.com
# [Not needed] Sets the "OpenAI-Organization" header field to support organization users (UI > this > '')
OPENAI_API_ORG_ID=MY_OPENAI_API_ORG_ID

# [Optional] Enables ElevenLabs credentials on the server side - for optional text-to-speech
ELEVENLABS_API_KEY=
ELEVENLABS_API_HOST=
ELEVENLABS_VOICE_ID=

# [Optional] Prodia credentials on the server side - for optional image generation
PRODIA_API_KEY=
```

---

This is the UI displayed:

![image](https://user-images.githubusercontent.com/46310946/234273549-8f08495c-0e1a-40bc-80af-b4d65ec460e3.png)

---

This is the log:

```
> big-agi@0.9.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Users\ming\projects\nextjs-chatgpt-app\.env
event - compiled client and server successfully in 851 ms (923 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 138 ms (924 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling / (client and server)...
event - compiled client and server successfully in 899 ms (1399 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling /api/openai/stream-chat (client and server)...
event - compiled successfully in 75 ms (79 modules)
 [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
}
wait  - compiling /api/openai/chat (client and server)...
event - compiled successfully in 55 ms (80 modules)
```

---

How to fix it? I can't find the interrelated document anymore.

Thanks in advance!

**Comment by enricoros** [comment]
Can you confirm that the connection to OpenAI APIs is working?

From the same machine, browse (Chrome/Firefox) to:
https://api.openai.com/v1/completions

And expect to see a message about messing API keys, like in this screenshot:

![Screenshot_20230425_141159_Chrome.jpg](https://user-images.githubusercontent.com/32999/234405221-05889210-224c-4be7-b75a-002e0cbc9ec2.jpg)


To confirm: in the .env file, those constants like MY_API_KEY are not literal, you're only using placeholders for the screenshot, right?

**Comment by fox20431** [comment]
Thank @enricoros! I confirmed I could connect the openai api:

![image](https://user-images.githubusercontent.com/46310946/234489196-0740d8fd-17a8-45e6-8009-0f294927039f.png)

and yes, the `NT_API_KEY` is placeholders, the key is worked(I can use it in the project online version).

**Comment by enricoros** [comment]
Very hard for me to debug tho. The problem still persists? I've updated lots of code tonight, wanna check with the latest?

I don't know how to remotely help debug. Do you have the output of all the browser console and the Nodejs console?

**Comment by fox20431** [comment]
OK, I just pulled the code, and the error changed.

This is browse displayed:

![image](https://user-images.githubusercontent.com/46310946/234495126-c293ac5c-e178-497b-9e42-46543152c8d1.png)

This is more about the network:

![image](https://user-images.githubusercontent.com/46310946/234495755-2f3bd7b2-dbe8-4194-b779-9ee979a8ad6f.png)
![image](https://user-images.githubusercontent.com/46310946/234495829-af9ce8ed-e8c8-46b1-8f21-fc636409dbac.png)
![image](https://user-images.githubusercontent.com/46310946/234495872-89b24f7d-3100-4905-8e16-fbcd754cc8eb.png)


This is the Nodejs console displayed:

![image](https://user-images.githubusercontent.com/46310946/234494941-8de1174f-ad55-4193-82ca-5681d6d4fc86.png)

**Comment by enricoros** [comment]
Hi @fox20431, did you make any progress? Is it the firewall?
Would be leaning on closing the issue otherwise, because doesn't seem to be an issue with the app.

**Comment by fox20431** [comment]
Hi @enricoros, this seems to have nothing to do with firewalls and systems; I use Linux to run the program, and has the same result under no firewall.

I guess this is because NodeJS does not follow the proxy rule.

--- The following is my conjecture ---

This is  the request flow is:

I send a request -> http://localhost:3000/api/openai/chat -> nodejs redirect the request -> openai host

but the proxy not working on nodejs, so I can't access the real host.

but due to that browse follow the proxy rule, so I can do it:

> From the same machine, browse (Chrome/Firefox) to:
> https://api.openai.com/v1/completions

---

If you think I'm right, I think this issue can be closed. Because I see the same feature request at another request.

**Comment by enricoros** [comment]
Yes, it's probably the proxy issue as you mention. Right now the app is using the "edge runtime", which is the faster for NextJS, but also it's a different implementation than Node.
Faster and low overhead and no cold start, but on the other hand it may be breaking proxy support? I'm not using proxies myself, I wonder how that would work.
