### ISSUE TITLE
Mismatching NPM/NVM versions

### ISSUE THREAD

**Issue by shadoath** [enricoros/big-agi#96]
After downloading the repo and running `npm i` I get the following message:

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
```

Can a `.nvmrc` file be added to make sure the right version of npm is used?

**Comment by enricoros** [comment]
> After downloading the repo and running `npm i` I get the following message:
> 
> ```
> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
> ```
> 
> Can a `.nvmrc` file be added to make sure the right version of npm is used?

Not familiar, what would be the contents for this file?

**Comment by enricoros** [comment]
Thanks. I don't have a way to test this, but should I just add a `.nvmrc` file, with just "18" being the contents?

**Comment by enricoros** [comment]
> When I run `npm -v` my output is `6.14.17`. This value changes as I move around projects depending on what is in the  [.nvmrc](https://github.com/nvm-sh/nvm#nvmrc) file. Which allows you to specify what version of node to use and subsequently the npm version corresponding with that.


I was discussing this issue with gpt, and it told me that there's a more generic way to solve this issue across package managers, not just nvm.

<< Specify the Node.js version in your `package.json` file using the "engines" field. This is a more general approach and is not tied to a specific version manager. >>

Is this correct?

**Comment by shadoath** [comment]
Both approaches would work. If you add the engines field, you would probably want to add `"engineStrict": true,` too.
I don't see it as either/or. Instead, I would do both. The `.nvmrc` gives those using nvm a quick way to grab and install the right version. Those who don't will get caught when they run `npm i` with the wrong version.
