### ISSUE TITLE
Feature: adding Web Searches

### ISSUE THREAD

**Issue by playhousehosting** [enricoros/big-agi#98]
Is it possible to add "web search" to this project? 

See link for details https://github.com/qunash/chatgpt-advanced

Thanks for all your hard work

**Comment by enricoros** [comment]
Good request, thanks for asking. We usually want to add features that other projects don't have.

We have one 'web' extension already, it's the ReAct thinking system, implemented by @fredliubojin - it's already in the code, but hidden to the users because being developed.

For your request, if you can think at an AWESOME way to have that web search experience, I will implement it.
 - I've seen the video on that link, but I dislike the UX
 - How can our version be better than, let's say, Bing+Chat?

Looking forward to good creative ideas on this 🙏

**Comment by playhousehosting** [comment]
My main reason for suggesting this feature was just to have more "up-to-date" results and also have the ability to search for weather results or current events. It could be an option that is turned on and off by each user. Just a few initial thoughts but I'll keep brain storming :-).

Thanks again for your work on this project. I will also check out the feature you mentioned as well.

**Comment by enricoros** [comment]
Here is a preview for you:
 - when the text box is empty, double-click on the "Chat" button - and you'll have the option to activate ReAct mode
 - this will let you search and reason on Wikipedia information (it's restricted on purpose)
 - try it out to see how it works, and to go back, simply double-click on the "Chat" button when the text box is empty

**Comment by enricoros** [comment]
Do they implement the Search feature using the Google Custom Search Engine? @fredliubojin  has something like this already running, but in his python project: https://github.com/fredliubojin/langchain_gradio

**Comment by playhousehosting** [comment]
> Here is a preview for you:
> 
> * when the text box is empty, double-click on the "Chat" button - and you'll have the option to activate ReAct mode
> * this will let you search and reason on Wikipedia information (it's restricted on purpose)
> * try it out to see how it works, and to go back, simply double-click on the "Chat" button when the text box is empty

I tested this feature and it is really cool just doesnt provide the accuracy of the websearch plug in. For example I asked who the Superbowl this year and it provided an incorrect response. Using "websearch " would have giving a more accurate response. Hope this helps. And thanks again for the response.

**Comment by playhousehosting** [comment]
> Do they implement the Search feature using the Google Custom Search Engine? @fredliubojin has something like this already running, but in his python project: https://github.com/fredliubojin/langchain_gradio

Im not 100% sure how it works to be honest

**Comment by enricoros** [comment]
@playhousehosting could you test the feature and let us know what you think? It's on main and big-agi.com

**Comment by playhousehosting** [comment]
Hello,

First I want to start off by saying thank you for adding this functionality! I truly think this project is the best

I've been testing all morning and it works really well. It provides the up todate information that I was looking for  :-) 

Additional feedback:
Would it be possible to add the citations as clickable links? For example. I ask for the cheapest house available in California according to Zillow. It provides me with a bunch of links but they were not clickable. Do you think it would be possible to make the citations clickable for ease of use?

**Comment by enricoros** [comment]
Hi @playhousehosting - oh really? sounds amazing! We were quite quick to add google support, thanks to @fredliubojin :)
Oh yes, it's a good point.

Can you attach a couple of screenshots of how you use this? I want to see the use cases, and provide the best UX

**Comment by playhousehosting** [comment]
Hello here is one example of how I use the web search feature. Let.me.knownif this helps I can provide other use cases as well. 
![Screenshot_20230427-192144](https://user-images.githubusercontent.com/126509681/235039637-4b153269-2768-49f3-848e-aea599a788e2.png)

**Comment by playhousehosting** [comment]
Here is how "web search" outputs results on another platform I've used that was really helpful. 1, 3 ,4 are clickable.  Hope this helps. 

![Screenshot_20230427-213043](https://user-images.githubusercontent.com/126509681/235054775-49d65ffc-bf9f-462d-9a28-b6b7acfc050e.png)

**Comment by enricoros** [comment]
Hi @playhousehosting - I've just cleaned up a bit, increase the depth of Google search as well - please reload the app to make sure you have the latest.

## How to turn on Link rendering - go to Settings and turn on `Markdown`
![image](https://user-images.githubusercontent.com/32999/235074340-1e5846e4-1ff1-4a12-a86f-8dfdd38c3f76.png)

This will turn this:
![image](https://user-images.githubusercontent.com/32999/235074474-6fe4bcad-7cd6-4a16-9bcc-1e6e9c3462cc.png)

Into this:
![image](https://user-images.githubusercontent.com/32999/235074425-fbb19ae0-7239-4f98-b4db-e3bfe9fad795.png)

Should we close this? @fredliubojin

**Comment by playhousehosting** [comment]
Thanks for the update! I just tried And I'm having a different result using 3.5 turbo. Mark down is turned on as well. 

![Screenshot_20230428-002121](https://user-images.githubusercontent.com/126509681/235081888-51ecf879-edfa-419e-889e-e49f1d9038e4.png)

**Comment by playhousehosting** [comment]
It doesn't seem to be consistent with generating links
![Screenshot_20230428-004039](https://user-images.githubusercontent.com/126509681/235085688-b00af6d6-f59b-424b-862b-784d26cb7eb3.png)

**Comment by enricoros** [comment]
Thanks for all the testing. With gpt4 is very consistent, but 3.5 was not following the system prompt as much. We tuned for gpt4 - do you have access to it?

Now you'll find a /react command in the app.

/react what happened to the SpaceX rocket last week?

Even easier to use. And better search/data. Shall we close this ticket and open others for improvement/ideas?

**Comment by playhousehosting** [comment]
Hello, unfortunately I do not have access to gpt 4 yet. Thank you for your hard work on this. Does that mean until I have gpt 4 I won't be able to use the new feature with this platform? 

Thanks

**Comment by playhousehosting** [comment]
Most people that will be using this on the site I'm hosting it on (chatwithgpt.app) will only have access to 3.5 API.

**Comment by enricoros** [comment]
Closing this item due to inactivity. The UI allows to select different LLMs, and newer models behave better. More Model options also.

**Comment by Norfeldt** [comment]
I have setup the google search and seem to be able to run it using `/react` command, but without this gpt-4 tell me that it can't search the web? Am I missing something?

(btw it's a great project 👌)

**Comment by enricoros** [comment]
@Norfeldt yes, it's just not wired up to GPT-4 as a tool. So browsing works with /browse or react, but not in any GPT-4 call.
Would not be hard to implement generic browsing from the llm.

**Comment by Norfeldt** [comment]
@enricoros thank you for (the awesome project and) the reply. I tried changing to 3.5 and have setup Google API key and Google CSE ID. But for some reason that isn't working.

<img width="1212" alt="Screenshot 2024-02-13 at 10 48 24" src="https://github.com/enricoros/big-AGI/assets/678806/f5384de0-77a9-4c88-9890-189583120f50">

While testing I have set the API key to be unrestricted and have also enabled some extra APIs

<img width="270" alt="Screenshot 2024-02-13 at 10 54 54" src="https://github.com/enricoros/big-AGI/assets/678806/1b3ea081-cf7a-4950-a64d-d017df365985">

Am I missing an API or something else?
